const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const { generateTestsFromSource, runTests } = require('../index');

const CLI_PATH = path.resolve(__dirname, '..', 'bin', 'themis.js');
const FIXTURES_DIR = path.join(__dirname, 'fixtures');
const GENERATED_MARKER = '// Generated by Themis code scan. Do not edit manually.';
const REACT_INDEX_SOURCE = `function useState(initialValue) {
  const value = typeof initialValue === 'function' ? initialValue() : initialValue;
  function setValue() {}
  return [value, setValue];
}

const Fragment = Symbol.for('react.fragment');

module.exports = {
  Fragment,
  useState
};
`;
const REACT_JSX_RUNTIME_SOURCE = `const Fragment = Symbol.for('react.fragment');

function jsx(type, props, key) {
  return {
    $$typeof: 'react.test.element',
    type,
    key: key || null,
    props: props || {}
  };
}

const jsxs = jsx;

module.exports = {
  Fragment,
  jsx,
  jsxs
};
`;

describe('code scan generation', () => {
  async function withProjectFixture(files, run) {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'themis-generate-'));

    for (const [relativePath, source] of Object.entries(files)) {
      const targetPath = path.join(tempDir, relativePath);
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });
      fs.writeFileSync(targetPath, source, 'utf8');
    }

    try {
      return await run({
        tempDir,
        resolvePath: (...parts) => path.join(tempDir, ...parts)
      });
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }

  async function withFixtureDirectory(name, run) {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'themis-generate-fixture-'));
    const sourceDir = path.join(FIXTURES_DIR, name);
    fs.cpSync(sourceDir, tempDir, { recursive: true });

    try {
      return await run({
        tempDir,
        resolvePath: (...parts) => path.join(tempDir, ...parts)
      });
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }

  function runCli(tempDir, args) {
    const result = spawnSync(process.execPath, [CLI_PATH, ...args], {
      cwd: tempDir,
      encoding: 'utf8',
      env: {
        ...process.env,
        NO_COLOR: '1'
      }
    });

    return {
      status: result.status,
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      output: `${result.stdout || ''}${result.stderr || ''}`
    };
  }

  function runCliJsonWithRetry(tempDir, args, attempts = 2) {
    let lastRun = null;
    for (let attempt = 0; attempt < attempts; attempt += 1) {
      const run = runCli(tempDir, args);
      lastRun = run;
      if (run.status !== 0) {
        continue;
      }

      try {
        const payload = JSON.parse(run.output);
        if (payload.summary && payload.summary.failed === 0) {
          return { run, payload };
        }
      } catch (error) {
        // Try once more if the subprocess emitted incomplete JSON.
      }
    }

    return { run: lastRun, payload: null };
  }

  function parseJsonOutput(result) {
    return JSON.parse(result.stdout || result.output);
  }

  function runGit(tempDir, args) {
    const result = spawnSync('git', args, {
      cwd: tempDir,
      encoding: 'utf8'
    });

    if (result.status !== 0) {
      throw new Error(`git ${args.join(' ')} failed: ${(result.stderr || result.stdout || '').trim()}`);
    }
  }

  function createMixedAppFixture() {
    return {
      'package.json': `{\n  "name": "themis-mixed-app-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/Button.tsx': `export interface ButtonProps {\n  label: string;\n  tone?: 'primary' | 'secondary';\n  disabled?: boolean;\n}\n\nexport function Button({ label, tone = 'primary', disabled = false }: ButtonProps) {\n  return <button data-tone={tone} disabled={disabled}>{label}</button>;\n}\n`,
      'src/components/Button.themis.json': `${JSON.stringify({
        componentProps: {
          Button: [
            {
              label: 'Ship it',
              tone: 'secondary',
              disabled: true
            }
          ]
        }
      }, null, 2)}\n`,
      'src/hooks/useToggle.ts': `import { useState } from 'react';\n\nexport function useToggle(initial = false) {\n  const [value, setValue] = useState(initial);\n\n  return {\n    value,\n    enable() {\n      setValue(true);\n    },\n    disable() {\n      setValue(false);\n    }\n  };\n}\n`,
      'src/hooks/useToggle.themis.json': `${JSON.stringify({
        hookArgs: {
          useToggle: [[true]]
        }
      }, null, 2)}\n`,
      'src/routes/ping.ts': `export async function GET(request, context = { params: {} }) {\n  const url = new URL(request.url);\n  return new Response(JSON.stringify({\n    ok: true,\n    path: url.pathname,\n    params: context.params || {}\n  }), {\n    status: 200,\n    headers: {\n      'content-type': 'application/json'\n    }\n  });\n}\n`,
      'src/routes/ping.themis.json': `${JSON.stringify({
        scenarios: ['route-handler'],
        routeRequests: {
          GET: [
            {
              method: 'GET',
              url: 'https://themis.test/api/ping?mode=beta'
            }
          ]
        },
        routeContext: {
          GET: [
            {
              params: {
                team: 'themis'
              }
            }
          ]
        }
      }, null, 2)}\n`,
      'src/services/math.ts': `export function add(a: number, b: number) {\n  return a + b;\n}\n\nexport function formatStatus(status = 'ready') {\n  return {\n    status,\n    upper: status.toUpperCase()\n  };\n}\n`,
      'src/services/math.themis.json': `${JSON.stringify({
        serviceArgs: {
          add: [[2, 3]],
          formatStatus: [['beta']]
        }
      }, null, 2)}\n`
    };
  }

  function createInteractiveReactFixture() {
    return {
      'package.json': `{\n  "name": "themis-interactive-react-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/CounterButton.tsx': `import { useState } from 'react';\n\nexport interface CounterButtonProps {\n  initial?: number;\n}\n\nexport function CounterButton({ initial = 0 }: CounterButtonProps) {\n  const [count, setCount] = useState(initial);\n\n  return <button data-count={count} onClick={() => setCount((value) => value + 1)}>Count {count}</button>;\n}\n`,
      'src/hooks/useToggle.ts': `import { useState } from 'react';\n\nexport function useToggle(initial = false) {\n  const [value, setValue] = useState(initial);\n\n  return {\n    value,\n    enable() {\n      setValue(true);\n    },\n    disable() {\n      setValue(false);\n    },\n    toggle() {\n      setValue((current) => !current);\n    }\n  };\n}\n`
    };
  }

  function createNextAppFixture() {
    return {
      'package.json': `{\n  "name": "themis-next-app-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'app/page.tsx': `import { useState } from 'react';\n\nexport default function HomePage({ searchParams = {}, params = {} }) {\n  const [open, setOpen] = useState(false);\n\n  return (\n    <main>\n      <button data-open={open} onClick={() => setOpen(true)}>Open</button>\n      <pre>{JSON.stringify({ searchParams, params, open })}</pre>\n    </main>\n  );\n}\n`,
      'app/api/health/route.ts': `export async function GET(request, context = { params: {} }) {\n  const url = new URL(request.url);\n  return new Response(JSON.stringify({\n    ok: true,\n    path: url.pathname,\n    params: context.params || {}\n  }), {\n    status: 200,\n    headers: {\n      'content-type': 'application/json'\n    }\n  });\n}\n`
    };
  }

  function createProviderDrivenFixture() {
    return {
      'package.json': `{\n  "name": "themis-provider-driven-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'themis.generate.js': `module.exports = {\n  providers: [\n    {\n      include: /src\\/components\\//,\n      componentProps: {\n        GreetingButton: [{ label: 'Launch' }]\n      },\n      componentInteractions: {\n        GreetingButton: [{ event: 'onClick', repeat: 2 }]\n      },\n      applyMocks({ scenario, mock, fn }) {\n        if (scenario !== 'react-component' || !mock || !fn) {\n          return;\n        }\n\n        mock('./src/services/greeter.ts', () => ({\n          getGreeting: fn(() => 'Mock hi')\n        }));\n      },\n      wrapRender({ element, exportName, scenario }) {\n        return {\n          $$typeof: 'react.test.element',\n          type: 'section',\n          key: null,\n          props: {\n            role: 'region',\n            'aria-label': exportName + ' ' + scenario,\n            'data-provider': 'wrapped',\n            children: element\n          }\n        };\n      }\n    },\n    {\n      include: /src\\/services\\//,\n      serviceArgs: {\n        loadGreeting: [[]]\n      },\n      applyMocks({ scenario, mock, fn }) {\n        if (scenario !== 'node-service' || !mock || !fn) {\n          return;\n        }\n\n        mock('./src/services/greeter.ts', () => ({\n          getGreeting: fn(() => 'Mock hi')\n        }));\n      }\n    },\n    {\n      include: /src\\/hooks\\//,\n      hookArgs: {\n        useRemoteToggle: [[false]]\n      },\n      hookInteractions: {\n        useRemoteToggle: [{ method: 'toggle', repeat: 2 }, { method: 'enable' }]\n      },\n      applyMocks({ scenario, mock, fn }) {\n        if (scenario !== 'react-hook' || !mock || !fn) {\n          return;\n        }\n\n        mock('./src/services/analytics.ts', () => ({\n          track: fn(() => 'tracked')\n        }));\n      }\n    }\n  ]\n};\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/GreetingButton.tsx': `import { useState } from 'react';\nimport { getGreeting } from '../services/greeter.ts';\n\nexport function GreetingButton({ label = 'Load' }) {\n  const [message, setMessage] = useState('idle');\n\n  return <button onClick={() => setMessage(getGreeting())}>{label}: {message}</button>;\n}\n`,
      'src/hooks/useRemoteToggle.ts': `import { useState } from 'react';\nimport { track } from '../services/analytics.ts';\n\nexport function useRemoteToggle(initial = false) {\n  const [value, setValue] = useState(initial);\n\n  return {\n    value,\n    toggle() {\n      track('toggle');\n      setValue((current) => !current);\n    },\n    enable() {\n      track('enable');\n      setValue(true);\n    }\n  };\n}\n`,
      'src/services/greeter.ts': `export function getGreeting() {\n  throw new Error('provider mock required');\n}\n`,
      'src/services/loadGreeting.ts': `import { getGreeting } from './greeter.ts';\n\nexport function loadGreeting() {\n  return getGreeting();\n}\n`,
      'src/services/analytics.ts': `export function track(name) {\n  return name;\n}\n`
    };
  }

  function createAsyncUiFlowFixture() {
    return {
      'package.json': `{\n  "name": "themis-async-ui-flow-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'themis.generate.js': `module.exports = {\n  providers: [\n    {\n      include: /src\\/components\\//,\n      componentProps: {\n        SignupForm: [{ endpoint: 'https://themis.test/api/signup', initialEmail: 'ada@themis.test' }]\n      },\n      componentFlows: {\n        SignupForm: [\n          {\n            label: 'submit signup',\n            event: 'onSubmit',\n            elementType: 'form',\n            awaitResult: true,\n            flushMicrotasks: 2,\n            expected: {\n              settledTextIncludes: 'saved'\n            }\n          }\n        ]\n      },\n      wrapRender({ element }) {\n        return {\n          $$typeof: 'react.test.element',\n          type: 'div',\n          key: null,\n          props: {\n            role: 'main',\n            'data-app-shell': 'themis',\n            children: element\n          }\n        };\n      },\n      applyMocks({ scenario, mockFetch }) {\n        if (scenario !== 'react-component' || !mockFetch) {\n          return;\n        }\n\n        mockFetch({ json: { state: 'saved' }, status: 201 });\n      }\n    }\n  ]\n};\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/SignupForm.tsx': `import { useState } from 'react';\n\nexport function SignupForm({ endpoint, initialEmail = 'ada@themis.test' }) {\n  const [email, setEmail] = useState(initialEmail);\n  const [status, setStatus] = useState('idle');\n\n  async function submit(event) {\n    event.preventDefault();\n    setStatus('loading');\n    const response = await fetch(endpoint, {\n      method: 'POST',\n      headers: {\n        'content-type': 'application/json'\n      },\n      body: JSON.stringify({ email })\n    });\n    const payload = await response.json();\n    setStatus(payload.state);\n  }\n\n  return (\n    <form onSubmit={submit}>\n      <label htmlFor=\"email\">Email</label>\n      <input id=\"email\" value={email} onInput={(event) => setEmail(event.target.value)} />\n      <button type=\"submit\">Send to {email || 'nobody'}</button>\n      <p role=\"status\">{status}</p>\n    </form>\n  );\n}\n`
    };
  }

  function createInferredAsyncUiFlowFixture() {
    return {
      'package.json': `{\n  "name": "themis-inferred-ui-flow-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/AsyncStatusForm.tsx': `import { useState } from 'react';\n\nexport function AsyncStatusForm() {\n  const [email, setEmail] = useState('ada@themis.test');\n  const [status, setStatus] = useState('idle');\n\n  async function submit(event) {\n    event.preventDefault();\n    setStatus('loading');\n    await Promise.resolve();\n    setStatus('saved');\n  }\n\n  return (\n    <form onSubmit={submit}>\n      <label htmlFor=\"email\">Email</label>\n      <input id=\"email\" value={email} onInput={(event) => setEmail(event.target.value)} />\n      <button type=\"submit\">Send {email}</button>\n      <p role=\"status\">{status}</p>\n    </form>\n  );\n}\n`
    };
  }

  function createProviderPresetFixture() {
    return {
      'package.json': `{\n  "name": "themis-provider-preset-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'themis.generate.js': `module.exports = {\n  providers: [\n    {\n      include: /src\\/components\\//,\n      router: {\n        path: '/teams/themis',\n        params: { team: 'themis' },\n        search: { tab: 'overview' },\n        name: 'dashboard',\n        history: ['/teams/themis', '/teams/themis?tab=overview'],\n        state: { from: 'overview' }\n      },\n      nextNavigation: {\n        pathname: '/dashboard',\n        params: { team: 'themis' },\n        searchParams: { tab: 'overview' },\n        segment: 'dashboard',\n        locale: 'en-US'\n      },\n      auth: {\n        user: 'ada',\n        state: 'authenticated',\n        session: { team: 'themis' },\n        roles: ['admin'],\n        permissions: ['teams:write']\n      },\n      reactQuery: {\n        clientName: 'themis-client',\n        state: { greeting: 'warm-cache' },\n        status: 'success',\n        fetchStatus: 'idle',\n        queries: ['dashboard']\n      },\n      zustand: {\n        name: 'ui-store',\n        state: { modalOpen: true },\n        selectors: ['modalOpen'],\n        actions: ['toggleModal']\n      },\n      redux: {\n        slice: 'session',\n        state: { user: 'ada' },\n        selectors: ['user'],\n        actions: ['session/login']\n      },\n      wrapRender({ element, withReduxStore }) {\n        return withReduxStore(element, {\n          slice: 'session',\n          state: { user: 'ada-override' }\n        });\n      }\n    }\n  ]\n};\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/Dashboard.tsx': `export function Dashboard() {\n  return <button>Launch dashboard</button>;\n}\n`
    };
  }

  function createRichUiFlowFixture() {
    return {
      'package.json': `{\n  "name": "themis-rich-ui-flow-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'themis.generate.js': `module.exports = {\n  providers: [\n    {\n      include: /src\\/components\\//,\n      componentFlows: {\n        RetryingSignupForm: [\n          {\n            label: 'empty disables submit',\n            event: 'onInput',\n            elementType: 'input',\n            target: { value: '' },\n            expected: {\n              attributes: { disabled: true },\n              rolesInclude: ['button']\n            }\n          },\n          {\n            label: 'restore input before submit',\n            event: 'onInput',\n            elementType: 'input',\n            target: { value: 'ada@themis.test' },\n            expected: {\n              attributes: { value: 'ada@themis.test' }\n            }\n          },\n          {\n            label: 'error after submit',\n            event: 'onSubmit',\n            elementType: 'form',\n            awaitResult: true,\n            flushMicrotasks: 2,\n            expected: {\n              immediateTextIncludes: 'loading',\n              settledTextIncludes: 'retry'\n            }\n          },\n          {\n            label: 'retry recovers',\n            event: 'onSubmit',\n            elementType: 'form',\n            awaitResult: true,\n            flushMicrotasks: 2,\n            expected: {\n              beforeTextIncludes: 'retry',\n              settledTextIncludes: 'saved',\n              textExcludes: 'error'\n            }\n          }\n        ]\n      },\n      applyMocks({ scenario, mockFetch }) {\n        if (scenario !== 'react-component' || !mockFetch) {\n          return;\n        }\n\n        let calls = 0;\n        mockFetch(() => {\n          calls += 1;\n          if (calls === 1) {\n            return { status: 500, json: { state: 'retry', error: true } };\n          }\n          return { status: 201, json: { state: 'saved' } };\n        });\n      }\n    }\n  ]\n};\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/RetryingSignupForm.tsx': `import { useState } from 'react';\n\nexport function RetryingSignupForm({ endpoint = 'https://themis.test/api/signup' }) {\n  const [email, setEmail] = useState('ada@themis.test');\n  const [status, setStatus] = useState('idle');\n\n  async function submit(event) {\n    event.preventDefault();\n    if (!email) {\n      setStatus('required');\n      return;\n    }\n    setStatus('loading');\n    const response = await fetch(endpoint, { method: 'POST', body: JSON.stringify({ email }) });\n    const payload = await response.json();\n    if (payload.error) {\n      setStatus('retry');\n      return;\n    }\n    setStatus(payload.state);\n  }\n\n  return (\n    <form onSubmit={submit}>\n      <label htmlFor=\"email\">Email</label>\n      <input id=\"email\" value={email} onInput={(event) => setEmail(event.target.value)} onFocus={() => setStatus('editing')} onKeyDown={(event) => {\n        if (event.key === 'Enter' && !email) {\n          setStatus('required');\n        }\n      }} />\n      <button type=\"submit\" disabled={!email}>Submit</button>\n      <p role=\"status\">{status}</p>\n    </form>\n  );\n}\n`
    };
  }

  test('generates deterministic tests, writes a source map artifact, and removes stale generated files', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  },\n  VERSION: '1.0.0'\n};\n`,
        'src/ui/widget.ts': `export class Widget {\n  render() {\n    return 'ready';\n  }\n}\n`,
        'src/internal.js': `const secret = 42;\n`
      },
      async ({ tempDir, resolvePath }) => {
        const initial = generateTestsFromSource(tempDir);

        expect(initial.generatedFiles.length).toBe(2);
        expect(initial.createdFiles.length).toBe(2);
        expect(initial.updatedFiles.length).toBe(0);
        expect(initial.removedFiles.length).toBe(0);
        expect(initial.skippedFiles.length).toBe(1);
        expect(initial.skippedFiles[0].reason).toContain('No runtime exports discovered');

        const mathTestPath = resolvePath('tests', 'generated', 'math.generated.test.js');
        const widgetTestPath = resolvePath('tests', 'generated', 'ui', 'widget.generated.test.js');
        expect(fs.existsSync(mathTestPath)).toBe(true);
        expect(fs.existsSync(widgetTestPath)).toBe(true);

        const generatedSource = fs.readFileSync(mathTestPath, 'utf8');
        expect(generatedSource.startsWith(GENERATED_MARKER)).toBe(true);
        expect(generatedSource).toContain("matches scanned export names");
        expect(generatedSource).toContain("node service adapter");
        expect(generatedSource).toContain("../../src/math.js");
        expect(generatedSource.includes('toMatchSnapshot')).toBe(false);

        const widgetTestSource = fs.readFileSync(widgetTestPath, 'utf8');
        expect(widgetTestSource.includes('toMatchSnapshot')).toBe(false);

        const mapPath = resolvePath('.themis', 'generate-map.json');
        expect(fs.existsSync(mapPath)).toBe(true);
        const mapPayload = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
        expect(mapPayload.schema).toBe('themis.generate.map.v1');
        expect(mapPayload.entries.length).toBe(2);
        expect(mapPayload.entries[0].sourceFile).toContain('src/');
        expect(mapPayload.entries[0].testFile).toContain('tests/generated/');

        const generatedRun = await runTests(initial.generatedFiles, {
          cwd: tempDir,
          maxWorkers: 1
        });

        expect(generatedRun.summary.failed).toBe(0);
        expect(generatedRun.summary.passed).toBe(5);

        const widgetSnapshotPath = resolvePath(
          'tests',
          'generated',
          'ui',
          '__snapshots__',
          'widget.generated.test.js.snapshots.json'
        );
        fs.mkdirSync(path.dirname(widgetSnapshotPath), { recursive: true });
        fs.writeFileSync(widgetSnapshotPath, '{}\n', 'utf8');
        expect(fs.existsSync(widgetSnapshotPath)).toBe(true);

        fs.rmSync(resolvePath('src', 'ui', 'widget.ts'));

        const rerun = generateTestsFromSource(tempDir);
        expect(rerun.generatedFiles.length).toBe(1);
        expect(rerun.removedFiles.length).toBe(1);
        expect(rerun.removedFiles[0]).toContain('widget.generated.test.js');
        expect(fs.existsSync(widgetTestPath)).toBe(false);
        expect(fs.existsSync(widgetSnapshotPath)).toBe(false);
      }
    );
  });

  test('generated tests fail with stale-regeneration guidance when the source changes after scan', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  }\n};\n`
      },
      async ({ tempDir, resolvePath }) => {
        const summary = generateTestsFromSource(tempDir);
        const testFile = resolvePath('tests', 'generated', 'math.generated.test.js');

        let runResult = await runTests(summary.generatedFiles, {
          cwd: tempDir,
          maxWorkers: 1
        });
        expect(runResult.summary.failed).toBe(0);

        fs.writeFileSync(
          resolvePath('src', 'math.js'),
          `module.exports = {\n  subtract(a, b) {\n    return a - b;\n  }\n};\n`,
          'utf8'
        );

        runResult = await runTests([testFile], {
          cwd: tempDir,
          maxWorkers: 1
        });

        expect(runResult.summary.failed).toBe(3);
        const failure = runResult.files[0].tests.find((entry) => entry.status === 'failed');
        expect(Boolean(failure)).toBe(true);
        expect(failure.error.message).toContain('stale');
        expect(failure.error.message).toContain('npx themis generate src/math.js');
      }
    );
  });

  test('supports review, update, clean, files, match-source, match-export, and changed workflows', async () => {
    await withProjectFixture(
      {
        'src/hooks/useToggle.ts': `export function useToggle(initial = false) {\n  return {\n    value: initial,\n    toggle() {\n      return !initial;\n    }\n  };\n}\n`,
        'src/services/math.ts': `export function add(a: number, b: number) {\n  return a + b;\n}\n\nexport function multiply(a: number, b: number) {\n  return a * b;\n}\n`,
        'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS"\n  }\n}\n`
      },
      async ({ tempDir, resolvePath }) => {
        runGit(tempDir, ['init']);
        runGit(tempDir, ['config', 'user.email', 'themis@example.com']);
        runGit(tempDir, ['config', 'user.name', 'Themis Tests']);
        runGit(tempDir, ['add', '.']);
        runGit(tempDir, ['commit', '-m', 'initial fixture']);

        const initial = runCli(tempDir, ['generate', 'src', '--json']);
        expect(initial.status).toBe(0);
        expect(parseJsonOutput(initial).summary.created).toBe(2);

        const review = runCli(tempDir, ['generate', 'src', '--review', '--match-export', 'useToggle', '--json']);
        expect(review.status).toBe(0);
        const reviewPayload = parseJsonOutput(review);
        expect(reviewPayload.mode.review).toBe(true);
        expect(reviewPayload.generatedFiles).toEqual(['tests/generated/hooks/useToggle.generated.test.js']);
        expect(reviewPayload.promptReady.summary).toContain('Review mode made no filesystem changes');

        fs.writeFileSync(
          resolvePath('src', 'services', 'math.ts'),
          `export function add(a: number, b: number) {\n  return a + b;\n}\n\nexport function multiply(a: number, b: number) {\n  return a * b * 2;\n}\n`,
          'utf8'
        );

        const changed = runCli(tempDir, ['generate', 'src', '--changed', '--match-source', 'services/', '--json']);
        expect(changed.status).toBe(0);
        const changedPayload = parseJsonOutput(changed);
        expect(changedPayload.mode.changed).toBe(true);
        expect(changedPayload.generatedFiles).toEqual(['tests/generated/services/math.generated.test.js']);
        expect(changedPayload.summary.updated).toBe(1);

        fs.writeFileSync(
          resolvePath('src', 'services', 'math.ts'),
          `export function add(a: number, b: number) {\n  return a + b + 1;\n}\n\nexport function multiply(a: number, b: number) {\n  return a * b * 2;\n}\n`,
          'utf8'
        );

        const updateOnly = runCli(tempDir, ['generate', 'src', '--files', 'src/services/math.ts', '--update', '--json']);
        expect(updateOnly.status).toBe(0);
        const updatePayload = parseJsonOutput(updateOnly);
        expect(updatePayload.mode.update).toBe(true);
        expect(updatePayload.generatedFiles).toEqual(['tests/generated/services/math.generated.test.js']);
        expect(updatePayload.summary.updated).toBe(1);

        const clean = runCli(tempDir, ['generate', 'src', '--files', 'src/services/math.ts', '--clean', '--json']);
        expect(clean.status).toBe(0);
        const cleanPayload = parseJsonOutput(clean);
        expect(cleanPayload.mode.clean).toBe(true);
        expect(cleanPayload.removedFiles).toContain('tests/generated/services/math.generated.test.js');
        expect(fs.existsSync(resolvePath('tests', 'generated', 'services', 'math.generated.test.js'))).toBe(false);
      }
    );
  });

  test('supports planning mode, scenario steering, confidence steering, and persisted handoff artifacts', async () => {
    await withProjectFixture(
      createMixedAppFixture(),
      async ({ tempDir, resolvePath }) => {
        const planned = runCli(tempDir, [
          'generate',
          'src',
          '--plan',
          '--scenario',
          'react-hook',
          '--min-confidence',
          'high'
        ]);
        expect(planned.status).toBe(0);

        const payload = parseJsonOutput(planned);
        expect(payload.mode.plan).toBe(true);
        expect(payload.mode.review).toBe(true);
        expect(payload.filters.scenario).toBe('react-hook');
        expect(payload.filters.minConfidence).toBe('high');
        expect(payload.generatedFiles).toEqual(['tests/generated/hooks/useToggle.generated.test.js']);
        expect(payload.promptReady.summary).toContain('Mode: plan');
        expect(payload.hints.plan).toBe('npx themis generate src --plan');

        const generateLastPath = resolvePath('.themis', 'generate-last.json');
        const handoffPath = resolvePath('.themis', 'generate-handoff.json');
        expect(fs.existsSync(generateLastPath)).toBe(true);
        expect(fs.existsSync(handoffPath)).toBe(true);

        const handoffPayload = JSON.parse(fs.readFileSync(handoffPath, 'utf8'));
        expect(handoffPayload.schema).toBe('themis.generate.handoff.v1');
        expect(handoffPayload.targets.length).toBe(1);
        expect(handoffPayload.targets[0].sourceFile).toBe('src/hooks/useToggle.ts');
        expect(handoffPayload.targets[0].scenarios).toContain('react-hook');
      }
    );
  });

  test('supports strict generation gates and writes a backlog artifact for unresolved work', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  }\n};\n`,
        'src/format.js': `module.exports = {\n  formatStatus(status) {\n    return {\n      status,\n      upper: String(status).toUpperCase()\n    };\n  }\n};\n`,
        'src/internal.js': `const secret = 42;\n`,
        'tests/generated/math.generated.test.js': `test('custom user test', () => {\n  expect(true).toBe(true);\n});\n`
      },
      async ({ tempDir, resolvePath }) => {
        const strictRun = runCli(tempDir, ['generate', 'src', '--review', '--strict', '--json']);
        expect(strictRun.status).toBe(1);

        const payload = parseJsonOutput(strictRun);
        expect(payload.gates.failed).toBe(true);
        expect(payload.gates.strict).toBe(true);
        expect(payload.gates.failOnSkips).toBe(true);
        expect(payload.gates.failOnConflicts).toBe(true);
        expect(payload.gates.requireConfidence).toBe('high');
        expect(payload.gates.failures.map((failure) => failure.code)).toEqual(['skips', 'conflicts', 'confidence']);
        expect(payload.backlog.summary.total).toBe(3);
        expect(payload.backlog.summary.errors).toBe(3);
        expect(payload.backlog.summary.skipped).toBe(1);
        expect(payload.backlog.summary.conflicts).toBe(1);
        expect(payload.backlog.summary.confidence).toBe(1);
        expect(payload.promptReady.unresolved.length).toBe(3);
        expect(payload.promptReady.unresolved.find((item) => item.type === 'conflict').suggestedCommand).toBe('npx themis generate src/math.js --force');

        const backlogPath = resolvePath('.themis', 'generate-backlog.json');
        expect(fs.existsSync(backlogPath)).toBe(true);

        const backlogPayload = JSON.parse(fs.readFileSync(backlogPath, 'utf8'));
        expect(backlogPayload.schema).toBe('themis.generate.backlog.v1');
        expect(backlogPayload.summary.total).toBe(3);
        expect(backlogPayload.items.find((item) => item.type === 'confidence').hintsFile).toBe('src/format.themis.json');
      }
    );
  });

  test('refuses to overwrite non-generated files without --force and replaces them with --force', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  }\n};\n`,
        'tests/generated/math.generated.test.js': `test('custom user test', () => {\n  expect(true).toBe(true);\n});\n`
      },
      async ({ tempDir, resolvePath }) => {
        const blocked = runCli(tempDir, ['generate', 'src']);
        expect(blocked.status).toBe(1);
        expect(blocked.output).toContain('Refusing to overwrite non-Themis file without --force');
        expect(blocked.output).toContain('Gate Failures');

        const forced = runCli(tempDir, ['generate', 'src', '--force']);
        expect(forced.status).toBe(0);
        expect(forced.output).toContain('THEMIS CODE SCAN COMPLETE');

        const rewritten = fs.readFileSync(resolvePath('tests', 'generated', 'math.generated.test.js'), 'utf8');
        expect(rewritten.startsWith(GENERATED_MARKER)).toBe(true);
      }
    );
  });

  test('supports one-command generation for a React-style TSX app', async () => {
    await withFixtureDirectory(
      'react-app',
      async ({ tempDir, resolvePath }) => {
        const generated = runCli(tempDir, ['generate', 'src']);
        expect(generated.status).toBe(0);
        expect(generated.output).toContain('THEMIS CODE SCAN COMPLETE');
        expect(generated.output).toContain('generated: 4');

        const buttonTestPath = resolvePath('tests', 'generated', 'components', 'Button.generated.test.js');
        expect(fs.existsSync(buttonTestPath)).toBe(true);

        const buttonTestSource = fs.readFileSync(buttonTestPath, 'utf8');
        expect(buttonTestSource).toContain('../../../src/components/Button.tsx');
        expect(buttonTestSource).toContain('react component adapter');

        const { run, payload } = runCliJsonWithRetry(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        expect(Boolean(payload)).toBe(true);
        expect(payload.summary.failed).toBe(0);
        expect(payload.summary.passed).toBe(16);
      }
    );
  });

  test('adds react interaction and hook state adapters for stateful React modules', async () => {
    await withProjectFixture(
      createInteractiveReactFixture(),
      async ({ tempDir }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--write-hints', '--json']);
        expect(generated.status).toBe(0);
        const payload = parseJsonOutput(generated);

        expect(payload.summary.generated).toBe(2);
        expect(payload.hintFiles.created).toEqual([
          'src/components/CounterButton.themis.json',
          'src/hooks/useToggle.themis.json'
        ]);

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        const runPayload = JSON.parse(run.output);
        const allTestNames = runPayload.files.flatMap((file) => file.tests.map((test) => test.fullName));
        expect(allTestNames.some((name) => name.includes('react component adapter') && name.includes('interaction contract'))).toBe(true);
        expect(allTestNames.some((name) => name.includes('react hook adapter') && name.includes('interaction contract'))).toBe(true);
      }
    );
  });

  test('detects Next app components and route handlers with framework-specific adapters', async () => {
    await withProjectFixture(
      createNextAppFixture(),
      async ({ tempDir }) => {
        const generated = runCli(tempDir, ['generate', 'app', '--write-hints', '--json']);
        expect(generated.status).toBe(0);
        const payload = parseJsonOutput(generated);

        expect(payload.summary.generated).toBe(2);
        expect(payload.entries.find((entry) => entry.sourceFile === 'app/page.tsx').moduleKind).toBe('next-app-component');
        expect(payload.entries.find((entry) => entry.sourceFile === 'app/api/health/route.ts').moduleKind).toBe('next-route-handler');
        expect(payload.entries.find((entry) => entry.sourceFile === 'app/page.tsx').scenarios[0].kind).toBe('next-app-component');
        expect(payload.entries.find((entry) => entry.sourceFile === 'app/api/health/route.ts').scenarios[0].kind).toBe('next-route-handler');

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        const runPayload = JSON.parse(run.output);
        const allTestNames = runPayload.files.flatMap((file) => file.tests.map((test) => test.fullName));
        expect(allTestNames.some((name) => name.includes('next app component adapter'))).toBe(true);
        expect(allTestNames.some((name) => name.includes('next interaction contract'))).toBe(true);
        expect(allTestNames.some((name) => name.includes('next route handler adapter'))).toBe(true);
      }
    );
  });

  test('uses project-level fixture and mock providers from themis.generate.js', async () => {
    await withProjectFixture(
      createProviderDrivenFixture(),
      async ({ tempDir, resolvePath }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--json']);
        expect(generated.status).toBe(0);
        const payload = parseJsonOutput(generated);

        expect(payload.summary.generated).toBe(5);
        const componentTestPath = resolvePath('tests', 'generated', 'components', 'GreetingButton.generated.test.js');
        const componentSource = fs.readFileSync(componentTestPath, 'utf8');
        expect(componentSource).toContain('PROJECT_PROVIDER_IMPORT');
        expect(componentSource).toContain('applyProjectProviderMocks');
        expect(componentSource).toContain('applyProjectProviderRender');
        expect(componentSource.includes('toMatchSnapshot')).toBe(false);

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        const runPayload = JSON.parse(run.output);
        expect(runPayload.summary.failed).toBe(0);
        const allTestNames = runPayload.files.flatMap((file) => file.tests.map((test) => test.fullName));
        expect(allTestNames.some((name) => name.includes('GreetingButton dom state contract'))).toBe(true);
      }
    );
  });

  test('writes a structured fix handoff artifact for failed generated tests', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  }\n};\n`
      },
      async ({ tempDir, resolvePath }) => {
        const generated = runCli(tempDir, ['generate', 'src']);
        expect(generated.status).toBe(0);

        fs.writeFileSync(
          resolvePath('src', 'math.js'),
          `module.exports = {\n  subtract(a, b) {\n    return a - b;\n  }\n};\n`,
          'utf8'
        );

        const run = runCli(tempDir, ['test', '--agent']);
        expect(run.status).toBe(1);

        const agentPayload = JSON.parse(run.output);
        expect(agentPayload.artifacts.fixHandoff).toBe('.themis/fix-handoff.json');
        expect(agentPayload.hints.repairGenerated).toBe('cat .themis/fix-handoff.json');

        const fixHandoff = JSON.parse(fs.readFileSync(resolvePath('.themis', 'fix-handoff.json'), 'utf8'));
        expect(fixHandoff.schema).toBe('themis.fix.handoff.v1');
        expect(fixHandoff.summary.generatedFailures).toBe(1);
        expect(fixHandoff.items[0].category).toBe('source-drift');
        expect(fixHandoff.items[0].sourceFile).toBe('src/math.js');
        expect(fixHandoff.items[0].suggestedCommand).toBe('npx themis generate src/math.js --update');
      }
    );
  });

  test('generates async behavioral UI flow contracts with provider-aware wrappers and mocks', async () => {
    await withProjectFixture(
      createAsyncUiFlowFixture(),
      async ({ tempDir, resolvePath }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--json']);
        expect(generated.status).toBe(0);
        const payload = parseJsonOutput(generated);

        expect(payload.summary.generated).toBe(1);
        const entry = payload.entries.find((item) => item.sourceFile === 'src/components/SignupForm.tsx');
        expect(entry.moduleKind).toBe('react-component');

        const componentTestPath = resolvePath('tests', 'generated', 'components', 'SignupForm.generated.test.js');
        const componentSource = fs.readFileSync(componentTestPath, 'utf8');
        expect(componentSource).toContain('behavioral flow contract');
        expect(componentSource).toContain('mockFetch');
        expect(componentSource).toContain('"settledTextIncludes": "saved"');
        expect(componentSource.includes('toMatchSnapshot')).toBe(false);

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        const runPayload = JSON.parse(run.output);
        expect(runPayload.summary.failed).toBe(0);

        const allTestNames = runPayload.files.flatMap((file) => file.tests.map((test) => test.fullName));
        expect(allTestNames.some((name) => name.includes('SignupForm behavioral flow contract'))).toBe(true);
      }
    );
  });

  test('infers richer stateful ui flows for async form components without hints', async () => {
    await withProjectFixture(createInferredAsyncUiFlowFixture(), async ({ tempDir, resolvePath }) => {
      const summary = generateTestsFromSource(tempDir);
      const generatedPath = resolvePath('tests', 'generated', 'components', 'AsyncStatusForm.generated.test.js');
      const generatedSource = fs.readFileSync(generatedPath, 'utf8');

      expect(summary.generatedFiles).toContain(generatedPath);
      expect(generatedSource).toContain('"event": "onInput"');
      expect(generatedSource).toContain('"event": "onSubmit"');
      expect(generatedSource).toContain('"immediateTextIncludes": "loading"');
      expect(generatedSource).toContain('"settledTextIncludes": "saved"');

      const result = await runTests([generatedPath], {
        cwd: tempDir,
        environment: 'jsdom',
        maxWorkers: 1,
        tsconfigPath: 'tsconfig.json'
      });

      expect(result.summary.failed).toBe(0);
      expect(result.summary.passed > 0).toBe(true);
    });
  });

  test('supports provider preset wrappers for router, react query, zustand, and redux patterns', async () => {
    await withProjectFixture(createProviderPresetFixture(), async ({ tempDir, resolvePath }) => {
      const summary = generateTestsFromSource(tempDir);
      const generatedPath = resolvePath('tests', 'generated', 'components', 'Dashboard.generated.test.js');
      const generatedSource = fs.readFileSync(generatedPath, 'utf8');

      expect(summary.generatedFiles).toContain(generatedPath);
      expect(generatedSource).toContain('PROJECT_PROVIDER_PRESETS');
      expect(generatedSource).toContain('"nextNavigation"');
      expect(generatedSource).toContain('"auth"');
      expect(generatedSource).toContain('"reactQuery"');
      expect(generatedSource).toContain('"zustand"');
      expect(generatedSource).toContain('"redux"');
      expect(generatedSource).toContain('"permissions"');
      expect(generatedSource).toContain('"queries"');
      expect(generatedSource).toContain('"history"');
      expect(generatedSource).toContain('"actions"');

      const result = await runTests([generatedPath], {
        cwd: tempDir,
        environment: 'jsdom',
        maxWorkers: 1,
        tsconfigPath: 'tsconfig.json'
      });

      expect(result.summary.failed).toBe(0);
      expect(result.summary.passed > 0).toBe(true);
    });
  });

  test('supports richer behavioral dom flows with empty, error, retry, and disabled state expectations', async () => {
    await withProjectFixture(createRichUiFlowFixture(), async ({ tempDir, resolvePath }) => {
      const summary = generateTestsFromSource(tempDir);
      const generatedPath = resolvePath('tests', 'generated', 'components', 'RetryingSignupForm.generated.test.js');
      const generatedSource = fs.readFileSync(generatedPath, 'utf8');

      expect(summary.generatedFiles).toContain(generatedPath);
      expect(generatedSource).toContain('"beforeTextIncludes": "retry"');
      expect(generatedSource).toContain('"textExcludes": "error"');
      expect(generatedSource).toContain('"attributes": {');
      expect(generatedSource).toContain('"rolesInclude": [');

      const result = await runTests([generatedPath], {
        cwd: tempDir,
        environment: 'jsdom',
        maxWorkers: 1,
        tsconfigPath: 'tsconfig.json'
      });

      expect(result.summary.failed).toBe(0);
      expect(result.summary.passed > 0).toBe(true);
    });
  });

  test('write-hints scaffolds missing hint sidecars and reuses them on repeat runs', async () => {
    await withFixtureDirectory(
      'react-app',
      async ({ tempDir, resolvePath }) => {
        const first = runCli(tempDir, ['generate', 'src', '--write-hints', '--json']);
        expect(first.status).toBe(0);

        const firstPayload = parseJsonOutput(first);
        expect(firstPayload.mode.writeHints).toBe(true);
        expect(firstPayload.hintFiles.created).toEqual([
          'src/components/Button.themis.json',
          'src/components/Card.themis.json',
          'src/hooks/useToggle.themis.json'
        ]);
        expect(firstPayload.hintFiles.updated).toEqual([]);
        expect(firstPayload.hintFiles.unchanged).toEqual([]);
        expect(firstPayload.hints.writeHints).toBe('npx themis generate src --write-hints');
        expect(firstPayload.entries.find((entry) => entry.sourceFile === 'src/components/Button.tsx').confidence).toBe('medium');
        expect(firstPayload.entries.find((entry) => entry.sourceFile === 'src/hooks/useToggle.ts').confidence).toBe('medium');

        const buttonHintPath = resolvePath('src', 'components', 'Button.themis.json');
        const hookHintPath = resolvePath('src', 'hooks', 'useToggle.themis.json');
        expect(fs.existsSync(buttonHintPath)).toBe(true);
        expect(fs.existsSync(hookHintPath)).toBe(true);

        const buttonHint = JSON.parse(fs.readFileSync(buttonHintPath, 'utf8'));
        expect(buttonHint.$meta.kind).toBe('scaffold');
        expect(buttonHint.componentProps.Button[0].label).toBe('themis');

        const second = runCli(tempDir, ['generate', 'src', '--write-hints', '--json']);
        expect(second.status).toBe(0);
        const secondPayload = parseJsonOutput(second);
        expect(secondPayload.hintFiles.created).toEqual([]);
        expect(secondPayload.hintFiles.updated).toEqual([]);
        expect(secondPayload.hintFiles.unchanged).toEqual([
          'src/components/Button.themis.json',
          'src/components/Card.themis.json',
          'src/hooks/useToggle.themis.json'
        ]);

        const { run, payload: runPayload } = runCliJsonWithRetry(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        expect(Boolean(runPayload)).toBe(true);
        expect(runPayload.summary.failed).toBe(0);
      }
    );
  });

  test('uses per-file hints to generate high-confidence React, route, and service adapters', async () => {
    await withProjectFixture(
      createMixedAppFixture(),
      async ({ tempDir }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--json']);
        expect(generated.status).toBe(0);

        const payload = parseJsonOutput(generated);
        expect(payload.summary.generated).toBe(4);
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/components/Button.tsx').confidence).toBe('high');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/hooks/useToggle.ts').confidence).toBe('high');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/routes/ping.ts').moduleKind).toBe('route-handler');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/services/math.ts').moduleKind).toBe('node-service');
        expect(payload.promptReady.prompt).toContain('CREATE src/routes/ping.ts');

        const mapPayload = JSON.parse(fs.readFileSync(path.join(tempDir, '.themis', 'generate-map.json'), 'utf8'));
        expect(mapPayload.entries.length).toBe(4);
        expect(mapPayload.entries.find((entry) => entry.sourceFile === 'src/routes/ping.ts').scenarios[0].kind).toBe('route-handler');

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        const runPayload = JSON.parse(run.output);
        expect(runPayload.summary.failed).toBe(0);
        expect(runPayload.summary.passed).toBe(16);

        const allTestNames = runPayload.files.flatMap((file) => file.tests.map((test) => test.fullName));
        expect(allTestNames.some((name) => name.includes('route handler adapter'))).toBe(true);
        expect(allTestNames.some((name) => name.includes('node service adapter'))).toBe(true);
        expect(allTestNames.some((name) => name.includes('dom state contract'))).toBe(true);
      }
    );
  });

  test('emits rich machine-readable generation payload with entries, artifacts, prompt-ready output, and confidence tiers', async () => {
    await withFixtureDirectory(
      'react-app',
      async ({ tempDir }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--json']);
        expect(generated.status).toBe(0);
        expect(generated.output.includes('THEMIS v')).toBe(false);

        const payload = parseJsonOutput(generated);
        expect(payload.schema).toBe('themis.generate.result.v1');
        expect(payload.mode.review).toBe(false);
        expect(payload.source.targetDir).toBe('src');
        expect(payload.source.outputDir).toBe('tests/generated');
        expect(payload.summary.scanned).toBe(4);
        expect(payload.summary.generated).toBe(4);
        expect(payload.summary.created).toBe(4);
        expect(payload.summary.updated).toBe(0);
        expect(payload.summary.unchanged).toBe(0);
        expect(payload.summary.removed).toBe(0);
        expect(payload.summary.skipped).toBe(0);
        expect(payload.summary.conflicts).toBe(0);
        expect(payload.generatedFiles).toContain('tests/generated/components/Button.generated.test.js');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/components/Button.tsx').scenarios[0].kind).toBe('react-component');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/hooks/useToggle.ts').scenarios[0].kind).toBe('react-hook');
        expect(payload.artifacts.generateMap).toBe('.themis/generate-map.json');
        expect(payload.artifacts.generateResult).toBe('.themis/generate-last.json');
        expect(payload.artifacts.generateHandoff).toBe('.themis/generate-handoff.json');
        expect(payload.mode.writeHints).toBe(false);
        expect(payload.hintFiles.created).toEqual([]);
        expect(payload.hints.writeHints).toBe('npx themis generate src --write-hints');
        expect(payload.promptReady.summary).toContain('Mode: generate');
        expect(payload.promptReady.targets.length).toBe(4);
        expect(payload.hints.plan).toBe('npx themis generate src --plan');
        expect(payload.hints.review).toBe('npx themis generate src --review --json');
      }
    );
  });
});
