const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const { generateTestsFromSource, runTests } = require('../index');

const CLI_PATH = path.resolve(__dirname, '..', 'bin', 'themis.js');
const FIXTURES_DIR = path.join(__dirname, 'fixtures');
const GENERATED_MARKER = '// Generated by Themis code scan. Do not edit manually.';
const REACT_INDEX_SOURCE = `function useState(initialValue) {
  const value = typeof initialValue === 'function' ? initialValue() : initialValue;
  function setValue() {}
  return [value, setValue];
}

const Fragment = Symbol.for('react.fragment');

module.exports = {
  Fragment,
  useState
};
`;
const REACT_JSX_RUNTIME_SOURCE = `const Fragment = Symbol.for('react.fragment');

function jsx(type, props, key) {
  return {
    $$typeof: 'react.test.element',
    type,
    key: key || null,
    props: props || {}
  };
}

const jsxs = jsx;

module.exports = {
  Fragment,
  jsx,
  jsxs
};
`;

describe('code scan generation', () => {
  async function withProjectFixture(files, run) {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'themis-generate-'));

    for (const [relativePath, source] of Object.entries(files)) {
      const targetPath = path.join(tempDir, relativePath);
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });
      fs.writeFileSync(targetPath, source, 'utf8');
    }

    try {
      return await run({
        tempDir,
        resolvePath: (...parts) => path.join(tempDir, ...parts)
      });
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }

  async function withFixtureDirectory(name, run) {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'themis-generate-fixture-'));
    const sourceDir = path.join(FIXTURES_DIR, name);
    fs.cpSync(sourceDir, tempDir, { recursive: true });

    try {
      return await run({
        tempDir,
        resolvePath: (...parts) => path.join(tempDir, ...parts)
      });
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }

  function runCli(tempDir, args) {
    const result = spawnSync(process.execPath, [CLI_PATH, ...args], {
      cwd: tempDir,
      encoding: 'utf8',
      env: {
        ...process.env,
        NO_COLOR: '1'
      }
    });

    return {
      status: result.status,
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      output: `${result.stdout || ''}${result.stderr || ''}`
    };
  }

  function parseJsonOutput(result) {
    return JSON.parse(result.stdout || result.output);
  }

  function runGit(tempDir, args) {
    const result = spawnSync('git', args, {
      cwd: tempDir,
      encoding: 'utf8'
    });

    if (result.status !== 0) {
      throw new Error(`git ${args.join(' ')} failed: ${(result.stderr || result.stdout || '').trim()}`);
    }
  }

  function createMixedAppFixture() {
    return {
      'package.json': `{\n  "name": "themis-mixed-app-fixture",\n  "private": true,\n  "version": "0.0.0"\n}\n`,
      'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS",\n    "jsx": "react-jsx"\n  }\n}\n`,
      'node_modules/react/index.js': REACT_INDEX_SOURCE,
      'node_modules/react/jsx-runtime.js': REACT_JSX_RUNTIME_SOURCE,
      'src/components/Button.tsx': `export interface ButtonProps {\n  label: string;\n  tone?: 'primary' | 'secondary';\n  disabled?: boolean;\n}\n\nexport function Button({ label, tone = 'primary', disabled = false }: ButtonProps) {\n  return <button data-tone={tone} disabled={disabled}>{label}</button>;\n}\n`,
      'src/components/Button.themis.json': `${JSON.stringify({
        componentProps: {
          Button: [
            {
              label: 'Ship it',
              tone: 'secondary',
              disabled: true
            }
          ]
        }
      }, null, 2)}\n`,
      'src/hooks/useToggle.ts': `import { useState } from 'react';\n\nexport function useToggle(initial = false) {\n  const [value, setValue] = useState(initial);\n\n  return {\n    value,\n    enable() {\n      setValue(true);\n    },\n    disable() {\n      setValue(false);\n    }\n  };\n}\n`,
      'src/hooks/useToggle.themis.json': `${JSON.stringify({
        hookArgs: {
          useToggle: [[true]]
        }
      }, null, 2)}\n`,
      'src/routes/ping.ts': `export async function GET(request, context = { params: {} }) {\n  const url = new URL(request.url);\n  return new Response(JSON.stringify({\n    ok: true,\n    path: url.pathname,\n    params: context.params || {}\n  }), {\n    status: 200,\n    headers: {\n      'content-type': 'application/json'\n    }\n  });\n}\n`,
      'src/routes/ping.themis.json': `${JSON.stringify({
        scenarios: ['route-handler'],
        routeRequests: {
          GET: [
            {
              method: 'GET',
              url: 'https://themis.test/api/ping?mode=beta'
            }
          ]
        },
        routeContext: {
          GET: [
            {
              params: {
                team: 'themis'
              }
            }
          ]
        }
      }, null, 2)}\n`,
      'src/services/math.ts': `export function add(a: number, b: number) {\n  return a + b;\n}\n\nexport function formatStatus(status = 'ready') {\n  return {\n    status,\n    upper: status.toUpperCase()\n  };\n}\n`,
      'src/services/math.themis.json': `${JSON.stringify({
        serviceArgs: {
          add: [[2, 3]],
          formatStatus: [['beta']]
        }
      }, null, 2)}\n`
    };
  }

  test('generates deterministic tests, writes a source map artifact, and removes stale generated files', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  },\n  VERSION: '1.0.0'\n};\n`,
        'src/ui/widget.ts': `export class Widget {\n  render() {\n    return 'ready';\n  }\n}\n`,
        'src/internal.js': `const secret = 42;\n`
      },
      async ({ tempDir, resolvePath }) => {
        const initial = generateTestsFromSource(tempDir);

        expect(initial.generatedFiles.length).toBe(2);
        expect(initial.createdFiles.length).toBe(2);
        expect(initial.updatedFiles.length).toBe(0);
        expect(initial.removedFiles.length).toBe(0);
        expect(initial.skippedFiles.length).toBe(1);
        expect(initial.skippedFiles[0].reason).toContain('No runtime exports discovered');

        const mathTestPath = resolvePath('tests', 'generated', 'math.generated.test.js');
        const widgetTestPath = resolvePath('tests', 'generated', 'ui', 'widget.generated.test.js');
        expect(fs.existsSync(mathTestPath)).toBe(true);
        expect(fs.existsSync(widgetTestPath)).toBe(true);

        const generatedSource = fs.readFileSync(mathTestPath, 'utf8');
        expect(generatedSource.startsWith(GENERATED_MARKER)).toBe(true);
        expect(generatedSource).toContain("matches scanned export names");
        expect(generatedSource).toContain("node service adapter");
        expect(generatedSource).toContain("../../src/math.js");

        const mapPath = resolvePath('.themis', 'generate-map.json');
        expect(fs.existsSync(mapPath)).toBe(true);
        const mapPayload = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
        expect(mapPayload.schema).toBe('themis.generate.map.v1');
        expect(mapPayload.entries.length).toBe(2);
        expect(mapPayload.entries[0].sourceFile).toContain('src/');
        expect(mapPayload.entries[0].testFile).toContain('tests/generated/');

        const generatedRun = await runTests(initial.generatedFiles, {
          cwd: tempDir,
          maxWorkers: 1
        });

        expect(generatedRun.summary.failed).toBe(0);
        expect(generatedRun.summary.passed).toBe(5);

        const widgetSnapshotPath = resolvePath(
          'tests',
          'generated',
          'ui',
          '__snapshots__',
          'widget.generated.test.js.snapshots.json'
        );
        expect(fs.existsSync(widgetSnapshotPath)).toBe(true);

        fs.rmSync(resolvePath('src', 'ui', 'widget.ts'));

        const rerun = generateTestsFromSource(tempDir);
        expect(rerun.generatedFiles.length).toBe(1);
        expect(rerun.removedFiles.length).toBe(1);
        expect(rerun.removedFiles[0]).toContain('widget.generated.test.js');
        expect(fs.existsSync(widgetTestPath)).toBe(false);
        expect(fs.existsSync(widgetSnapshotPath)).toBe(false);
      }
    );
  });

  test('generated tests fail with stale-regeneration guidance when the source changes after scan', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  }\n};\n`
      },
      async ({ tempDir, resolvePath }) => {
        const summary = generateTestsFromSource(tempDir);
        const testFile = resolvePath('tests', 'generated', 'math.generated.test.js');

        let runResult = await runTests(summary.generatedFiles, {
          cwd: tempDir,
          maxWorkers: 1
        });
        expect(runResult.summary.failed).toBe(0);

        fs.writeFileSync(
          resolvePath('src', 'math.js'),
          `module.exports = {\n  subtract(a, b) {\n    return a - b;\n  }\n};\n`,
          'utf8'
        );

        runResult = await runTests([testFile], {
          cwd: tempDir,
          maxWorkers: 1
        });

        expect(runResult.summary.failed).toBe(3);
        const failure = runResult.files[0].tests.find((entry) => entry.status === 'failed');
        expect(Boolean(failure)).toBe(true);
        expect(failure.error.message).toContain('stale');
        expect(failure.error.message).toContain('npx themis generate src/math.js');
      }
    );
  });

  test('supports review, update, clean, files, match-source, match-export, and changed workflows', async () => {
    await withProjectFixture(
      {
        'src/hooks/useToggle.ts': `export function useToggle(initial = false) {\n  return {\n    value: initial,\n    toggle() {\n      return !initial;\n    }\n  };\n}\n`,
        'src/services/math.ts': `export function add(a: number, b: number) {\n  return a + b;\n}\n\nexport function multiply(a: number, b: number) {\n  return a * b;\n}\n`,
        'tsconfig.json': `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "CommonJS"\n  }\n}\n`
      },
      async ({ tempDir, resolvePath }) => {
        runGit(tempDir, ['init']);
        runGit(tempDir, ['config', 'user.email', 'themis@example.com']);
        runGit(tempDir, ['config', 'user.name', 'Themis Tests']);
        runGit(tempDir, ['add', '.']);
        runGit(tempDir, ['commit', '-m', 'initial fixture']);

        const initial = runCli(tempDir, ['generate', 'src', '--json']);
        expect(initial.status).toBe(0);
        expect(parseJsonOutput(initial).summary.created).toBe(2);

        const review = runCli(tempDir, ['generate', 'src', '--review', '--match-export', 'useToggle', '--json']);
        expect(review.status).toBe(0);
        const reviewPayload = parseJsonOutput(review);
        expect(reviewPayload.mode.review).toBe(true);
        expect(reviewPayload.generatedFiles).toEqual(['tests/generated/hooks/useToggle.generated.test.js']);
        expect(reviewPayload.promptReady.summary).toContain('Review mode made no filesystem changes');

        fs.writeFileSync(
          resolvePath('src', 'services', 'math.ts'),
          `export function add(a: number, b: number) {\n  return a + b;\n}\n\nexport function multiply(a: number, b: number) {\n  return a * b * 2;\n}\n`,
          'utf8'
        );

        const changed = runCli(tempDir, ['generate', 'src', '--changed', '--match-source', 'services/', '--json']);
        expect(changed.status).toBe(0);
        const changedPayload = parseJsonOutput(changed);
        expect(changedPayload.mode.changed).toBe(true);
        expect(changedPayload.generatedFiles).toEqual(['tests/generated/services/math.generated.test.js']);
        expect(changedPayload.summary.updated).toBe(1);

        fs.writeFileSync(
          resolvePath('src', 'services', 'math.ts'),
          `export function add(a: number, b: number) {\n  return a + b + 1;\n}\n\nexport function multiply(a: number, b: number) {\n  return a * b * 2;\n}\n`,
          'utf8'
        );

        const updateOnly = runCli(tempDir, ['generate', 'src', '--files', 'src/services/math.ts', '--update', '--json']);
        expect(updateOnly.status).toBe(0);
        const updatePayload = parseJsonOutput(updateOnly);
        expect(updatePayload.mode.update).toBe(true);
        expect(updatePayload.generatedFiles).toEqual(['tests/generated/services/math.generated.test.js']);
        expect(updatePayload.summary.updated).toBe(1);

        const clean = runCli(tempDir, ['generate', 'src', '--files', 'src/services/math.ts', '--clean', '--json']);
        expect(clean.status).toBe(0);
        const cleanPayload = parseJsonOutput(clean);
        expect(cleanPayload.mode.clean).toBe(true);
        expect(cleanPayload.removedFiles).toContain('tests/generated/services/math.generated.test.js');
        expect(fs.existsSync(resolvePath('tests', 'generated', 'services', 'math.generated.test.js'))).toBe(false);
      }
    );
  });

  test('supports planning mode, scenario steering, confidence steering, and persisted handoff artifacts', async () => {
    await withProjectFixture(
      createMixedAppFixture(),
      async ({ tempDir, resolvePath }) => {
        const planned = runCli(tempDir, [
          'generate',
          'src',
          '--plan',
          '--scenario',
          'react-hook',
          '--min-confidence',
          'high'
        ]);
        expect(planned.status).toBe(0);

        const payload = parseJsonOutput(planned);
        expect(payload.mode.plan).toBe(true);
        expect(payload.mode.review).toBe(true);
        expect(payload.filters.scenario).toBe('react-hook');
        expect(payload.filters.minConfidence).toBe('high');
        expect(payload.generatedFiles).toEqual(['tests/generated/hooks/useToggle.generated.test.js']);
        expect(payload.promptReady.summary).toContain('Mode: plan');
        expect(payload.hints.plan).toBe('npx themis generate src --plan');

        const generateLastPath = resolvePath('.themis', 'generate-last.json');
        const handoffPath = resolvePath('.themis', 'generate-handoff.json');
        expect(fs.existsSync(generateLastPath)).toBe(true);
        expect(fs.existsSync(handoffPath)).toBe(true);

        const handoffPayload = JSON.parse(fs.readFileSync(handoffPath, 'utf8'));
        expect(handoffPayload.schema).toBe('themis.generate.handoff.v1');
        expect(handoffPayload.targets.length).toBe(1);
        expect(handoffPayload.targets[0].sourceFile).toBe('src/hooks/useToggle.ts');
        expect(handoffPayload.targets[0].scenarios).toContain('react-hook');
      }
    );
  });

  test('refuses to overwrite non-generated files without --force and replaces them with --force', async () => {
    await withProjectFixture(
      {
        'src/math.js': `module.exports = {\n  add(a, b) {\n    return a + b;\n  }\n};\n`,
        'tests/generated/math.generated.test.js': `test('custom user test', () => {\n  expect(true).toBe(true);\n});\n`
      },
      async ({ tempDir, resolvePath }) => {
        const blocked = runCli(tempDir, ['generate', 'src']);
        expect(blocked.status).toBe(1);
        expect(blocked.output).toContain('Refusing to overwrite non-Themis file');

        const forced = runCli(tempDir, ['generate', 'src', '--force']);
        expect(forced.status).toBe(0);
        expect(forced.output).toContain('THEMIS CODE SCAN COMPLETE');

        const rewritten = fs.readFileSync(resolvePath('tests', 'generated', 'math.generated.test.js'), 'utf8');
        expect(rewritten.startsWith(GENERATED_MARKER)).toBe(true);
      }
    );
  });

  test('supports one-command generation for a React-style TSX app', async () => {
    await withFixtureDirectory(
      'react-app',
      async ({ tempDir, resolvePath }) => {
        const generated = runCli(tempDir, ['generate', 'src']);
        expect(generated.status).toBe(0);
        expect(generated.output).toContain('THEMIS CODE SCAN COMPLETE');
        expect(generated.output).toContain('generated: 4');

        const buttonTestPath = resolvePath('tests', 'generated', 'components', 'Button.generated.test.js');
        expect(fs.existsSync(buttonTestPath)).toBe(true);

        const buttonTestSource = fs.readFileSync(buttonTestPath, 'utf8');
        expect(buttonTestSource).toContain('../../../src/components/Button.tsx');
        expect(buttonTestSource).toContain('react component adapter');

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);

        const payload = JSON.parse(run.output);
        expect(payload.summary.failed).toBe(0);
        expect(payload.summary.passed).toBe(11);
      }
    );
  });

  test('uses per-file hints to generate high-confidence React, route, and service adapters', async () => {
    await withProjectFixture(
      createMixedAppFixture(),
      async ({ tempDir }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--json']);
        expect(generated.status).toBe(0);

        const payload = parseJsonOutput(generated);
        expect(payload.summary.generated).toBe(4);
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/components/Button.tsx').confidence).toBe('high');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/hooks/useToggle.ts').confidence).toBe('high');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/routes/ping.ts').moduleKind).toBe('route-handler');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/services/math.ts').moduleKind).toBe('node-service');
        expect(payload.promptReady.prompt).toContain('CREATE src/routes/ping.ts');

        const mapPayload = JSON.parse(fs.readFileSync(path.join(tempDir, '.themis', 'generate-map.json'), 'utf8'));
        expect(mapPayload.entries.length).toBe(4);
        expect(mapPayload.entries.find((entry) => entry.sourceFile === 'src/routes/ping.ts').scenarios[0].kind).toBe('route-handler');

        const run = runCli(tempDir, ['test', '--json']);
        expect(run.status).toBe(0);
        const runPayload = JSON.parse(run.output);
        expect(runPayload.summary.failed).toBe(0);
        expect(runPayload.summary.passed).toBe(13);

        const allTestNames = runPayload.files.flatMap((file) => file.tests.map((test) => test.fullName));
        expect(allTestNames.some((name) => name.includes('route handler adapter'))).toBe(true);
        expect(allTestNames.some((name) => name.includes('node service adapter'))).toBe(true);
      }
    );
  });

  test('emits rich machine-readable generation payload with entries, artifacts, prompt-ready output, and confidence tiers', async () => {
    await withFixtureDirectory(
      'react-app',
      async ({ tempDir }) => {
        const generated = runCli(tempDir, ['generate', 'src', '--json']);
        expect(generated.status).toBe(0);
        expect(generated.output.includes('THEMIS v')).toBe(false);

        const payload = parseJsonOutput(generated);
        expect(payload.schema).toBe('themis.generate.result.v1');
        expect(payload.mode.review).toBe(false);
        expect(payload.source.targetDir).toBe('src');
        expect(payload.source.outputDir).toBe('tests/generated');
        expect(payload.summary.scanned).toBe(4);
        expect(payload.summary.generated).toBe(4);
        expect(payload.summary.created).toBe(4);
        expect(payload.summary.updated).toBe(0);
        expect(payload.summary.unchanged).toBe(0);
        expect(payload.summary.removed).toBe(0);
        expect(payload.summary.skipped).toBe(0);
        expect(payload.summary.conflicts).toBe(0);
        expect(payload.generatedFiles).toContain('tests/generated/components/Button.generated.test.js');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/components/Button.tsx').scenarios[0].kind).toBe('react-component');
        expect(payload.entries.find((entry) => entry.sourceFile === 'src/hooks/useToggle.ts').scenarios[0].kind).toBe('react-hook');
        expect(payload.artifacts.generateMap).toBe('.themis/generate-map.json');
        expect(payload.artifacts.generateResult).toBe('.themis/generate-last.json');
        expect(payload.artifacts.generateHandoff).toBe('.themis/generate-handoff.json');
        expect(payload.promptReady.summary).toContain('Mode: generate');
        expect(payload.promptReady.targets.length).toBe(4);
        expect(payload.hints.plan).toBe('npx themis generate src --plan');
        expect(payload.hints.review).toBe('npx themis generate src --review --json');
      }
    );
  });
});
