const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const ts = require('typescript');

const GENERATED_MARKER = '// Generated by Themis code scan. Do not edit manually.';
const GENERATED_HELPER_NAME = '_themis.contract-runtime.js';
const GENERATED_MAP_ARTIFACT = path.join('.themis', 'generate-map.json');
const GENERATED_RESULT_ARTIFACT = path.join('.themis', 'generate-last.json');
const GENERATED_HANDOFF_ARTIFACT = path.join('.themis', 'generate-handoff.json');
const SOURCE_EXTENSIONS = new Set(['.js', '.jsx', '.ts', '.tsx']);
const TEST_FILE_PATTERN = /\.(test|spec)\.(js|jsx|ts|tsx)$/;
const HTTP_METHOD_EXPORTS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'];
const SCENARIO_PRIORITY = ['react-component', 'react-hook', 'route-handler', 'node-service', 'module-contract'];
const CONFIDENCE_PRIORITY = ['low', 'medium', 'high'];
const HINT_FILE_SUFFIX = '.themis.json';

const GENERATED_HELPER_SOURCE = `${GENERATED_MARKER}
const crypto = require('crypto');
const fs = require('fs');

function listExportNames(moduleExports) {
  const keys = getEnumerableKeys(moduleExports);
  const namedKeys = keys.filter((key) => key !== '__esModule' && key !== 'default').sort();
  const hasExplicitDefault = keys.includes('default');
  const needsImplicitDefault = hasImplicitDefaultExport(moduleExports, namedKeys);
  const names = [];

  if (hasExplicitDefault || needsImplicitDefault) {
    names.push('default');
  }

  names.push(...namedKeys);
  return names;
}

function buildModuleContract(moduleExports) {
  const names = listExportNames(moduleExports);
  const contract = {};

  for (const name of names) {
    contract[name] = normalizeModuleValue(readExportValue(moduleExports, name));
  }

  return contract;
}

function readExportValue(moduleExports, name) {
  if (name === 'default') {
    if (
      moduleExports &&
      (typeof moduleExports === 'object' || typeof moduleExports === 'function') &&
      Object.prototype.hasOwnProperty.call(moduleExports, 'default')
    ) {
      return moduleExports.default;
    }

    return moduleExports;
  }

  return moduleExports[name];
}

function getEnumerableKeys(value) {
  if (!value || (typeof value !== 'object' && typeof value !== 'function')) {
    return [];
  }

  return Object.keys(value).sort();
}

function hasImplicitDefaultExport(moduleExports, namedKeys) {
  if (moduleExports === null || moduleExports === undefined) {
    return true;
  }

  if (typeof moduleExports === 'function') {
    return true;
  }

  if (typeof moduleExports !== 'object') {
    return true;
  }

  if (Array.isArray(moduleExports)) {
    return true;
  }

  return namedKeys.length === 0;
}

function normalizeModuleValue(value) {
  if (value === null) {
    return { kind: 'null' };
  }

  const primitiveType = typeof value;
  if (primitiveType === 'undefined') {
    return { kind: 'undefined' };
  }
  if (primitiveType === 'string' || primitiveType === 'number' || primitiveType === 'boolean') {
    return { kind: primitiveType, value };
  }
  if (primitiveType === 'bigint') {
    return { kind: 'bigint', value: String(value) };
  }
  if (primitiveType === 'symbol') {
    return { kind: 'symbol', value: String(value) };
  }
  if (primitiveType === 'function') {
    return normalizeFunction(value);
  }

  if (Array.isArray(value)) {
    return {
      kind: 'array',
      length: value.length,
      itemTypes: [...new Set(value.map(classifyValue))].sort()
    };
  }

  if (value instanceof Date) {
    return { kind: 'date' };
  }
  if (value instanceof RegExp) {
    return { kind: 'regexp', source: value.source, flags: value.flags };
  }
  if (value instanceof Map) {
    return { kind: 'map', size: value.size };
  }
  if (value instanceof Set) {
    return { kind: 'set', size: value.size };
  }
  if (isPlainObject(value)) {
    return { kind: 'object', keys: Object.keys(value).sort() };
  }

  return {
    kind: 'instance',
    constructor: getConstructorName(value),
    keys: Object.keys(value).sort()
  };
}

function normalizeBehaviorValue(value, seen = new Set()) {
  if (value === null || value === undefined) {
    return value;
  }

  const primitiveType = typeof value;
  if (primitiveType === 'string' || primitiveType === 'number' || primitiveType === 'boolean') {
    return value;
  }
  if (primitiveType === 'bigint') {
    return { kind: 'bigint', value: String(value) };
  }
  if (primitiveType === 'symbol') {
    return { kind: 'symbol', value: String(value) };
  }
  if (primitiveType === 'function') {
    return normalizeFunction(value);
  }

  if (seen.has(value)) {
    return { kind: 'circular' };
  }
  seen.add(value);

  try {
    if (isReactLikeElement(value)) {
      return {
        kind: 'element',
        type: normalizeElementType(value.type),
        key: value.key === undefined ? null : value.key,
        props: normalizeBehaviorValue(value.props || {}, seen)
      };
    }

    if (Array.isArray(value)) {
      return value.map((item) => normalizeBehaviorValue(item, seen));
    }

    if (value instanceof Date) {
      return { kind: 'date', value: value.toISOString() };
    }
    if (value instanceof RegExp) {
      return { kind: 'regexp', source: value.source, flags: value.flags };
    }
    if (value instanceof Map) {
      return {
        kind: 'map',
        entries: [...value.entries()].map(([key, entryValue]) => ([
          normalizeBehaviorValue(key, seen),
          normalizeBehaviorValue(entryValue, seen)
        ]))
      };
    }
    if (value instanceof Set) {
      return {
        kind: 'set',
        values: [...value.values()].map((entryValue) => normalizeBehaviorValue(entryValue, seen))
      };
    }
    if (isPlainObject(value)) {
      const normalized = {};
      for (const key of Object.keys(value).sort()) {
        normalized[key] = normalizeBehaviorValue(value[key], seen);
      }
      return normalized;
    }

    return {
      kind: 'instance',
      constructor: getConstructorName(value),
      keys: normalizeBehaviorValue(Object.keys(value).sort(), seen)
    };
  } finally {
    seen.delete(value);
  }
}

async function normalizeRouteResult(value) {
  if (typeof Response !== 'undefined' && value instanceof Response) {
    const headers = {};
    for (const [key, headerValue] of value.headers.entries()) {
      headers[key] = headerValue;
    }

    const text = await value.clone().text();
    const body = tryParseJson(text);

    return {
      kind: 'response',
      status: value.status,
      statusText: value.statusText,
      redirected: value.redirected,
      headers,
      body: body === null ? text : body
    };
  }

  return normalizeBehaviorValue(value);
}

function createRequestFromSpec(spec) {
  const requestSpec = spec || {};
  const headers = { ...(requestSpec.headers || {}) };
  let body = undefined;

  if (requestSpec.json !== undefined) {
    if (!Object.prototype.hasOwnProperty.call(headers, 'content-type')) {
      headers['content-type'] = 'application/json';
    }
    body = JSON.stringify(requestSpec.json);
  } else if (requestSpec.body !== undefined) {
    body = requestSpec.body;
  }

  return new Request(requestSpec.url, {
    method: requestSpec.method || 'GET',
    headers,
    body
  });
}

function assertSourceFreshness(sourceFile, expectedHash, sourceLabel, regenerateCommand) {
  const currentHash = hashSourceFile(sourceFile);
  if (currentHash === expectedHash) {
    return;
  }

  throw new Error(
    'Themis generated test is stale for ' + sourceLabel +
    '. Run: ' + regenerateCommand +
    '. Expected source hash ' + expectedHash +
    ' but found ' + currentHash + '.'
  );
}

function hashSourceFile(sourceFile) {
  return crypto.createHash('sha1').update(fs.readFileSync(sourceFile, 'utf8')).digest('hex');
}

function tryParseJson(value) {
  if (!value) {
    return null;
  }

  try {
    return JSON.parse(value);
  } catch (error) {
    return null;
  }
}

function normalizeElementType(type) {
  if (typeof type === 'string') {
    return type;
  }
  if (typeof type === 'symbol') {
    return String(type);
  }
  if (typeof type === 'function') {
    return type.name || '(anonymous)';
  }
  return normalizeBehaviorValue(type);
}

function normalizeFunction(value) {
  const ownKeys = Object.keys(value).sort();
  const prototypeKeys = value.prototype && value.prototype !== Object.prototype
    ? Object.getOwnPropertyNames(value.prototype).filter((key) => key !== 'constructor').sort()
    : [];

  return {
    kind: isClassLike(value) ? 'class' : 'function',
    name: value.name || '(anonymous)',
    arity: value.length,
    ownKeys,
    prototypeKeys
  };
}

function classifyValue(value) {
  if (value === null) {
    return 'null';
  }
  if (Array.isArray(value)) {
    return 'array';
  }
  if (value instanceof Date) {
    return 'date';
  }
  if (value instanceof RegExp) {
    return 'regexp';
  }
  if (value instanceof Map) {
    return 'map';
  }
  if (value instanceof Set) {
    return 'set';
  }

  const type = typeof value;
  if (type !== 'object') {
    return type;
  }

  if (isPlainObject(value)) {
    return 'object';
  }

  return 'instance:' + getConstructorName(value);
}

function getConstructorName(value) {
  if (!value || !value.constructor || !value.constructor.name) {
    return 'Object';
  }
  return value.constructor.name;
}

function isPlainObject(value) {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function isClassLike(value) {
  return Function.prototype.toString.call(value).startsWith('class ');
}

function isReactLikeElement(value) {
  return value && typeof value === 'object' && value.$$typeof === 'react.test.element';
}

module.exports = {
  listExportNames,
  buildModuleContract,
  readExportValue,
  normalizeBehaviorValue,
  normalizeRouteResult,
  createRequestFromSpec,
  assertSourceFreshness
};
`;

function generateTestsFromSource(cwd, options = {}) {
  const projectRoot = path.resolve(cwd || process.cwd());
  const normalizedOptions = normalizeGenerateOptions(projectRoot, options);
  const scanTarget = resolveScanTarget(projectRoot, normalizedOptions.targetDir || 'src');
  const outputDir = path.resolve(projectRoot, normalizedOptions.outputDir || path.join('tests', 'generated'));
  const helperFile = path.join(outputDir, GENERATED_HELPER_NAME);
  const mapFile = path.resolve(projectRoot, GENERATED_MAP_ARTIFACT);
  const resultArtifactFile = path.resolve(projectRoot, GENERATED_RESULT_ARTIFACT);
  const handoffArtifactFile = path.resolve(projectRoot, GENERATED_HANDOFF_ARTIFACT);
  const existingMap = readGenerateMap(mapFile, projectRoot);
  const changedSet = normalizedOptions.changed ? collectChangedPaths(projectRoot) : null;
  const candidateFiles = selectSourceFiles({
    scanTarget,
    outputDir,
    projectRoot,
    options: normalizedOptions,
    changedSet
  });
  const analyses = [];
  const skippedFiles = [];
  const selectedSourceKeys = new Set(candidateFiles.map((file) => safeRealpath(file)));
  const existingEntryMap = new Map(existingMap.entries.map((entry) => [entry.sourceKey, entry]));
  const hasSelectionFilters = hasTargetedSelection(normalizedOptions, scanTarget);

  for (const file of candidateFiles) {
    const hints = readHintFile(file);
    const analysis = analyzeSourceFile(file);
    analysis.hints = hints;
    analysis.hintsFile = hints ? resolveHintFilePath(file) : null;
    analysis.sourceHash = createSourceHash(analysis.source);
    analysis.relativeFile = formatPathForDisplay(projectRoot, file);

    applyHintExportFilters(analysis);

    if (!analysis.hasRuntimeExports) {
      skippedFiles.push({
        file,
        reason: analysis.skipReason || 'No runtime exports discovered.',
        stage: 'analysis'
      });
      continue;
    }

    if (normalizedOptions.matchExport && !matchesExportFilter(analysis, normalizedOptions.matchExport)) {
      skippedFiles.push({
        file,
        reason: `No exported runtime symbol matched ${normalizedOptions.matchExport}.`,
        stage: 'filter'
      });
      continue;
    }

    analysis.scenarios = resolveScenarioPlans(analysis);
    analysis.moduleKind = pickPrimaryScenario(analysis.scenarios);
    analysis.confidence = pickOverallConfidence(analysis.scenarios);

    if (normalizedOptions.scenario && !analysis.scenarios.some((scenario) => scenario.kind === normalizedOptions.scenario)) {
      skippedFiles.push({
        file,
        reason: `No scenario matched ${normalizedOptions.scenario}.`,
        stage: 'filter'
      });
      continue;
    }

    if (normalizedOptions.minConfidence && !isConfidenceAtLeast(analysis.confidence, normalizedOptions.minConfidence)) {
      skippedFiles.push({
        file,
        reason: `Confidence ${analysis.confidence} is below ${normalizedOptions.minConfidence}.`,
        stage: 'filter'
      });
      continue;
    }

    analysis.outputFile = resolveGeneratedTestPath(outputDir, scanTarget.mirrorBase, analysis.file);
    analyses.push(analysis);
  }

  const plans = [];
  const removedPlans = [];

  if (!hasSelectionFilters && !normalizedOptions.clean) {
    for (const existingEntry of existingMap.entries) {
      if (selectedSourceKeys.has(existingEntry.sourceKey)) {
        continue;
      }

      removedPlans.push({
        sourceKey: existingEntry.sourceKey,
        sourceFile: path.resolve(projectRoot, existingEntry.sourceFile),
        file: path.resolve(projectRoot, existingEntry.testFile),
        reason: 'Source file was removed from the full scan target.'
      });
    }
  }

  for (const skipped of skippedFiles) {
    if (skipped.stage !== 'analysis') {
      continue;
    }
    const sourceKey = safeRealpath(skipped.file);
    const existing = existingEntryMap.get(sourceKey);
    if (!existing) {
      continue;
    }

    removedPlans.push({
      sourceKey,
      sourceFile: path.resolve(projectRoot, existing.sourceFile),
      file: path.resolve(projectRoot, existing.testFile),
      reason: 'Source no longer exposes runtime exports.'
    });
  }

  for (const analysis of analyses) {
    const sourceKey = safeRealpath(analysis.file);
    const existing = existingEntryMap.get(sourceKey);
    const content = renderGeneratedTest({
      projectRoot,
      helperFile,
      outputFile: analysis.outputFile,
      analysis
    });
    const existingContent = fs.existsSync(analysis.outputFile)
      ? fs.readFileSync(analysis.outputFile, 'utf8')
      : null;

    let action = 'create';
    if (existingContent !== null) {
      action = existingContent === content ? 'unchanged' : 'update';
    }

    if (normalizedOptions.update && !fs.existsSync(analysis.outputFile)) {
      skippedFiles.push({
        file: analysis.file,
        reason: 'Update mode only refreshes existing generated files.',
        stage: 'mode'
      });
      continue;
    }

    if (existingContent !== null && !existingContent.startsWith(GENERATED_MARKER) && !normalizedOptions.force) {
      if (normalizedOptions.review) {
        plans.push(buildConflictPlan(analysis, content, action, projectRoot));
        continue;
      }

      throw new Error(
        `Refusing to overwrite non-Themis file: ${analysis.outputFile}. Use --force to replace it.`
      );
    }

    plans.push(buildPlan(analysis, content, action, existing, projectRoot));
  }

  if (normalizedOptions.clean) {
    const cleanTargets = resolveCleanTargets({
      analyses,
      existingMap,
      projectRoot,
      selectedSourceKeys,
      hasSelectionFilters,
      changedSet
    });

    for (const cleanTarget of cleanTargets) {
      removedPlans.push(cleanTarget);
    }

    plans.length = 0;
  }

  const mergedMapEntries = mergeGenerateMapEntries({
    existingEntries: existingMap.entries,
    plans,
    removedPlans,
    review: normalizedOptions.review,
    clean: normalizedOptions.clean,
    projectRoot
  });

  const createdFiles = [];
  const updatedFiles = [];
  const unchangedFiles = [];
  const conflictFiles = [];

  for (const plan of plans) {
    if (plan.action === 'conflict') {
      conflictFiles.push(plan.outputFile);
      continue;
    }

    if (plan.action === 'create') {
      createdFiles.push(plan.outputFile);
    } else if (plan.action === 'update') {
      updatedFiles.push(plan.outputFile);
    } else {
      unchangedFiles.push(plan.outputFile);
    }
  }

  let removedFiles = [];
  let helperRemoved = false;

  if (!normalizedOptions.review) {
    const expectedManagedFiles = new Set();

    if (mergedMapEntries.length > 0 && !normalizedOptions.clean) {
      fs.mkdirSync(outputDir, { recursive: true });
      writeManagedFile(helperFile, GENERATED_HELPER_SOURCE, { force: normalizedOptions.force });
      expectedManagedFiles.add(safeRealpath(helperFile));
    }

    for (const plan of plans) {
      if (plan.action === 'conflict') {
        continue;
      }

      if (plan.action === 'create' || plan.action === 'update') {
        writeManagedFile(plan.outputFile, plan.content, { force: normalizedOptions.force });
      }
    }

    for (const entry of mergedMapEntries) {
      expectedManagedFiles.add(safeRealpath(path.resolve(projectRoot, entry.testFile)));
    }

    const explicitRemoved = removePlannedFiles(removedPlans, outputDir);
    removedFiles = cleanupStaleGeneratedFiles(outputDir, expectedManagedFiles, explicitRemoved);

    if (mergedMapEntries.length > 0) {
      writeGenerateMap(mapFile, projectRoot, scanTarget, outputDir, mergedMapEntries);
    } else {
      removeGenerateMap(mapFile);
      helperRemoved = removeManagedHelper(helperFile, outputDir);
    }
  }

  const entries = buildSummaryEntries({
    plans,
    removedPlans,
    projectRoot,
    review: normalizedOptions.review
  });
  const summary = {
    targetDir: scanTarget.requestedPath,
    outputDir,
    helperFile,
    mapFile,
    scannedFiles: candidateFiles,
    generatedFiles: plans
      .filter((plan) => plan.action !== 'conflict')
      .map((plan) => plan.outputFile),
    removedFiles,
    skippedFiles,
    createdFiles,
    updatedFiles,
    unchangedFiles,
    cleanedFiles: normalizedOptions.clean ? removedFiles : [],
    conflictFiles,
    entries,
    review: normalizedOptions.review,
    update: normalizedOptions.update,
    clean: normalizedOptions.clean,
    changed: normalizedOptions.changed,
    plan: normalizedOptions.plan,
    filters: buildFilterSummary(normalizedOptions, projectRoot),
    artifacts: {
      generateMap: mapFile,
      helperFile,
      generateResult: resultArtifactFile,
      generateHandoff: handoffArtifactFile
    },
    prompt: buildPromptSummary({
      projectRoot,
      plan: normalizedOptions.plan,
      review: normalizedOptions.review,
      update: normalizedOptions.update,
      clean: normalizedOptions.clean,
      createdFiles,
      updatedFiles,
      unchangedFiles,
      removedFiles,
      skippedFiles,
      conflictFiles,
      targetDir: scanTarget.requestedPath
    }),
    helperRemoved
  };

  return summary;
}

function buildGeneratePayload(summary, cwd) {
  const projectRoot = path.resolve(cwd || process.cwd());
  const promptReady = buildPromptReadyPayload(summary, projectRoot);

  return {
    schema: 'themis.generate.result.v1',
    mode: {
      review: summary.review,
      update: summary.update,
      clean: summary.clean,
      changed: summary.changed,
      plan: Boolean(summary.plan)
    },
    source: {
      targetDir: formatPathForDisplay(projectRoot, summary.targetDir),
      outputDir: formatPathForDisplay(projectRoot, summary.outputDir)
    },
    filters: summary.filters,
    summary: {
      scanned: summary.scannedFiles.length,
      generated: summary.generatedFiles.length,
      created: summary.createdFiles.length,
      updated: summary.updatedFiles.length,
      unchanged: summary.unchangedFiles.length,
      removed: summary.removedFiles.length,
      skipped: summary.skippedFiles.length,
      conflicts: summary.conflictFiles.length
    },
    scannedFiles: summary.scannedFiles.map((file) => formatPathForDisplay(projectRoot, file)),
    generatedFiles: summary.generatedFiles.map((file) => formatPathForDisplay(projectRoot, file)),
    removedFiles: summary.removedFiles.map((file) => formatPathForDisplay(projectRoot, file)),
    skippedFiles: summary.skippedFiles.map((entry) => ({
      file: formatPathForDisplay(projectRoot, entry.file),
      reason: entry.reason,
      stage: entry.stage
    })),
    conflictFiles: summary.conflictFiles.map((file) => formatPathForDisplay(projectRoot, file)),
    entries: summary.entries.map((entry) => ({
      action: entry.action,
      sourceFile: formatPathForDisplay(projectRoot, entry.sourceFile),
      testFile: entry.testFile ? formatPathForDisplay(projectRoot, entry.testFile) : null,
      moduleKind: entry.moduleKind,
      confidence: entry.confidence,
      exactExports: entry.exactExports,
      exportNames: entry.exportNames,
      hintsFile: entry.hintsFile ? formatPathForDisplay(projectRoot, entry.hintsFile) : null,
      sourceHash: entry.sourceHash,
      scenarios: entry.scenarios.map((scenario) => ({
        kind: scenario.kind,
        confidence: scenario.confidence,
        exports: scenario.exports,
        caseCount: scenario.caseCount
      })),
      reason: entry.reason || null
    })),
    artifacts: {
      generateMap: formatPathForDisplay(projectRoot, summary.artifacts.generateMap),
      helperFile: formatPathForDisplay(projectRoot, summary.artifacts.helperFile),
      generateResult: formatPathForDisplay(projectRoot, summary.artifacts.generateResult),
      generateHandoff: formatPathForDisplay(projectRoot, summary.artifacts.generateHandoff)
    },
    promptReady,
    hints: {
      runTests: 'npx themis test',
      plan: `npx themis generate ${formatPathForDisplay(projectRoot, summary.targetDir)} --plan`,
      review: `npx themis generate ${formatPathForDisplay(projectRoot, summary.targetDir)} --review --json`,
      updateOnly: `npx themis generate ${formatPathForDisplay(projectRoot, summary.targetDir)} --update`,
      clean: `npx themis generate ${formatPathForDisplay(projectRoot, summary.targetDir)} --clean`,
      changed: `npx themis generate ${formatPathForDisplay(projectRoot, summary.targetDir)} --changed`,
      fileTarget: 'npx themis generate src/path/to/file.ts'
    }
  };
}

function buildGenerateHandoff(payload) {
  return {
    schema: 'themis.generate.handoff.v1',
    source: payload.source,
    filters: payload.filters,
    summary: payload.summary,
    artifacts: {
      generateMap: payload.artifacts.generateMap,
      generateResult: payload.artifacts.generateResult
    },
    targets: payload.promptReady.targets,
    nextActions: payload.promptReady.nextActions,
    prompt: payload.promptReady.prompt
  };
}

function writeGenerateArtifacts(summary, cwd) {
  const projectRoot = path.resolve(cwd || process.cwd());
  const payload = buildGeneratePayload(summary, projectRoot);
  const handoff = buildGenerateHandoff(payload);

  fs.mkdirSync(path.dirname(summary.artifacts.generateResult), { recursive: true });
  fs.writeFileSync(summary.artifacts.generateResult, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
  fs.writeFileSync(summary.artifacts.generateHandoff, `${JSON.stringify(handoff, null, 2)}\n`, 'utf8');

  return { payload, handoff };
}

function normalizeGenerateOptions(projectRoot, options) {
  const outputDir = options.outputDir ? path.resolve(projectRoot, options.outputDir) : undefined;

  return {
    targetDir: options.targetDir || 'src',
    outputDir,
    force: Boolean(options.force),
    review: Boolean(options.review || options.plan),
    update: Boolean(options.update),
    clean: Boolean(options.clean),
    changed: Boolean(options.changed),
    plan: Boolean(options.plan),
    scenario: normalizeScenarioOption(options.scenario),
    minConfidence: normalizeConfidenceOption(options.minConfidence),
    matchSource: compileOptionalRegex(options.matchSource, '--match-source'),
    matchExport: compileOptionalRegex(options.matchExport, '--match-export'),
    include: compileOptionalRegex(options.include, '--include'),
    exclude: compileOptionalRegex(options.exclude, '--exclude'),
    files: normalizeFileSelection(projectRoot, options.files)
  };
}

function compileOptionalRegex(value, label) {
  if (!value) {
    return null;
  }

  try {
    return new RegExp(value);
  } catch (error) {
    throw new Error(`Invalid ${label} regex: ${value}`);
  }
}

function normalizeFileSelection(projectRoot, files) {
  if (!files) {
    return null;
  }

  const values = Array.isArray(files)
    ? files
    : String(files)
      .split(',')
      .map((entry) => entry.trim())
      .filter(Boolean);

  if (values.length === 0) {
    return null;
  }

  return values.map((entry) => path.resolve(projectRoot, entry));
}

function normalizeScenarioOption(value) {
  if (!value) {
    return null;
  }

  if (!SCENARIO_PRIORITY.includes(value)) {
    throw new Error(
      `Invalid --scenario value: ${value}. Use one of: ${SCENARIO_PRIORITY.join(', ')}.`
    );
  }

  return value;
}

function normalizeConfidenceOption(value) {
  if (!value) {
    return null;
  }

  if (!CONFIDENCE_PRIORITY.includes(value)) {
    throw new Error(
      `Invalid --min-confidence value: ${value}. Use one of: ${CONFIDENCE_PRIORITY.join(', ')}.`
    );
  }

  return value;
}

function isConfidenceAtLeast(confidence, minimum) {
  return CONFIDENCE_PRIORITY.indexOf(confidence) >= CONFIDENCE_PRIORITY.indexOf(minimum);
}

function resolveScanTarget(projectRoot, targetDir) {
  const requestedPath = path.resolve(projectRoot, targetDir);

  if (!fs.existsSync(requestedPath)) {
    throw new Error(`Generate target not found: ${formatPathForDisplay(projectRoot, requestedPath)}`);
  }

  const stat = fs.statSync(requestedPath);
  if (stat.isDirectory()) {
    return {
      requestedPath,
      isFile: false,
      mirrorBase: requestedPath
    };
  }

  if (!stat.isFile() || !isEligibleSourceFile(requestedPath)) {
    throw new Error(`Generate target is not a supported source file: ${formatPathForDisplay(projectRoot, requestedPath)}`);
  }

  return {
    requestedPath,
    isFile: true,
    mirrorBase: inferMirrorBase(projectRoot, requestedPath)
  };
}

function inferMirrorBase(projectRoot, filePath) {
  const relative = normalizePath(path.relative(projectRoot, filePath));
  const segments = relative.split('/');

  if (segments[0] === 'src') {
    return path.join(projectRoot, 'src');
  }

  return path.dirname(filePath);
}

function selectSourceFiles({ scanTarget, outputDir, projectRoot, options, changedSet }) {
  const files = [];

  if (scanTarget.isFile) {
    files.push(scanTarget.requestedPath);
  } else {
    discoverSourceFiles(scanTarget.requestedPath, outputDir, files);
  }

  const selected = files.filter((file) => {
    if (options.files && !options.files.some((selectedFile) => safeRealpath(selectedFile) === safeRealpath(file))) {
      return false;
    }

    const relativeFile = formatPathForDisplay(projectRoot, file);

    if (options.include && !options.include.test(relativeFile)) {
      return false;
    }
    if (options.exclude && options.exclude.test(relativeFile)) {
      return false;
    }
    if (options.matchSource && !options.matchSource.test(relativeFile)) {
      return false;
    }
    if (changedSet && !changedSet.has(safeRealpath(file))) {
      return false;
    }

    return true;
  });

  return selected.sort();
}

function collectChangedPaths(projectRoot) {
  let output;

  try {
    output = execFileSync(
      'git',
      ['status', '--short', '--untracked-files=all'],
      { cwd: projectRoot, encoding: 'utf8' }
    );
  } catch (error) {
    throw new Error('--changed requires a git worktree.');
  }

  const changed = new Set();
  for (const rawLine of String(output).split('\n')) {
    if (!rawLine.trim()) {
      continue;
    }

    const status = rawLine.slice(0, 2);
    const remainder = rawLine.slice(3).trim();
    const target = remainder.includes(' -> ') ? remainder.split(' -> ').pop() : remainder;
    const resolved = path.resolve(projectRoot, target);
    changed.add(safeRealpath(resolved));

    if (status.includes('R')) {
      const previous = remainder.split(' -> ')[0];
      changed.add(safeRealpath(path.resolve(projectRoot, previous)));
    }
  }

  return changed;
}

function analyzeSourceFile(filePath) {
  const source = fs.readFileSync(filePath, 'utf8');
  const sourceFile = ts.createSourceFile(
    filePath,
    source,
    ts.ScriptTarget.Latest,
    true,
    resolveScriptKind(filePath)
  );
  const typeIndex = collectTypeIndex(sourceFile);
  const state = {
    file: filePath,
    source,
    exportNames: new Set(),
    exportMap: new Map(),
    exactExports: true,
    hasRuntimeExports: false,
    skipReason: null,
    importsReact: false,
    usesJsx: path.extname(filePath).toLowerCase() === '.jsx' || path.extname(filePath).toLowerCase() === '.tsx'
  };

  for (const statement of sourceFile.statements) {
    collectImports(statement, state);
    collectExports(statement, state, typeIndex);
  }

  if (!state.hasRuntimeExports) {
    return {
      file: filePath,
      source,
      exportNames: [],
      exportEntries: [],
      exactExports: false,
      hasRuntimeExports: false,
      skipReason: 'No runtime exports discovered.',
      importsReact: state.importsReact,
      usesJsx: state.usesJsx
    };
  }

  const exportEntries = [...state.exportMap.values()].sort((a, b) => a.exportedName.localeCompare(b.exportedName));

  return {
    file: filePath,
    source,
    exportNames: [...state.exportNames].sort(),
    exportEntries,
    exactExports: state.exactExports,
    hasRuntimeExports: true,
    skipReason: null,
    importsReact: state.importsReact,
    usesJsx: state.usesJsx
  };
}

function collectImports(statement, state) {
  if (ts.isImportDeclaration(statement)) {
    const moduleName = readModuleSpecifier(statement.moduleSpecifier);
    if (moduleName === 'react' || moduleName === 'react/jsx-runtime') {
      state.importsReact = true;
    }
    return;
  }

  if (!ts.isVariableStatement(statement)) {
    return;
  }

  for (const declaration of statement.declarationList.declarations) {
    if (
      declaration.initializer &&
      ts.isCallExpression(declaration.initializer) &&
      ts.isIdentifier(declaration.initializer.expression) &&
      declaration.initializer.expression.text === 'require'
    ) {
      const moduleName = declaration.initializer.arguments[0] ? readKnownPropertyName(declaration.initializer.arguments[0]) : null;
      if (moduleName === 'react' || moduleName === 'react/jsx-runtime') {
        state.importsReact = true;
      }
    }
  }
}

function collectTypeIndex(sourceFile) {
  const index = new Map();

  for (const statement of sourceFile.statements) {
    if (ts.isInterfaceDeclaration(statement)) {
      const fields = readTypeMembers(statement.members, index);
      if (fields) {
        index.set(statement.name.text, fields);
      }
      continue;
    }

    if (ts.isTypeAliasDeclaration(statement) && ts.isTypeLiteralNode(statement.type)) {
      const fields = readTypeMembers(statement.type.members, index);
      if (fields) {
        index.set(statement.name.text, fields);
      }
    }
  }

  return index;
}

function readTypeMembers(members, typeIndex) {
  const fields = [];

  for (const member of members) {
    if (!ts.isPropertySignature(member) || !member.name) {
      continue;
    }

    const propertyName = getPropertyName(member.name);
    if (!propertyName) {
      continue;
    }

    const descriptor = resolveTypeDescriptor(member.type, typeIndex);
    fields.push({
      name: propertyName,
      optional: Boolean(member.questionToken),
      sampleValue: descriptor.sampleValue,
      inferredType: descriptor.inferredType
    });
  }

  return fields;
}

function resolveTypeDescriptor(typeNode, typeIndex) {
  if (!typeNode) {
    return { inferredType: 'unknown', sampleValue: undefined };
  }

  if (typeNode.kind === ts.SyntaxKind.StringKeyword) {
    return { inferredType: 'string', sampleValue: 'themis' };
  }
  if (typeNode.kind === ts.SyntaxKind.NumberKeyword) {
    return { inferredType: 'number', sampleValue: 1 };
  }
  if (typeNode.kind === ts.SyntaxKind.BooleanKeyword) {
    return { inferredType: 'boolean', sampleValue: false };
  }
  if (typeNode.kind === ts.SyntaxKind.AnyKeyword || typeNode.kind === ts.SyntaxKind.UnknownKeyword) {
    return { inferredType: 'unknown', sampleValue: undefined };
  }
  if (ts.isArrayTypeNode(typeNode)) {
    return { inferredType: 'array', sampleValue: [] };
  }
  if (ts.isTypeLiteralNode(typeNode)) {
    return {
      inferredType: 'object',
      sampleValue: buildObjectSample(readTypeMembers(typeNode.members, typeIndex))
    };
  }
  if (ts.isLiteralTypeNode(typeNode)) {
    return {
      inferredType: typeof typeNode.literal.text === 'string' ? 'string' : 'literal',
      sampleValue: readLiteralNodeValue(typeNode.literal)
    };
  }
  if (ts.isUnionTypeNode(typeNode)) {
    for (const innerType of typeNode.types) {
      const descriptor = resolveTypeDescriptor(innerType, typeIndex);
      if (descriptor.sampleValue !== undefined) {
        return descriptor;
      }
    }
    return { inferredType: 'unknown', sampleValue: undefined };
  }
  if (ts.isTypeReferenceNode(typeNode) && ts.isIdentifier(typeNode.typeName)) {
    const referenceName = typeNode.typeName.text;
    if (referenceName === 'Array') {
      return { inferredType: 'array', sampleValue: [] };
    }
    if (referenceName === 'Record' || referenceName === 'Readonly' || referenceName === 'Partial') {
      return { inferredType: 'object', sampleValue: {} };
    }
    if (referenceName === 'Promise') {
      return { inferredType: 'promise', sampleValue: undefined };
    }

    const fields = typeIndex.get(referenceName);
    if (fields) {
      return {
        inferredType: 'object',
        sampleValue: buildObjectSample(fields),
        objectFields: fields
      };
    }
  }

  return { inferredType: 'unknown', sampleValue: undefined };
}

function collectExports(statement, state, typeIndex) {
  if (ts.isFunctionDeclaration(statement) || ts.isClassDeclaration(statement) || ts.isEnumDeclaration(statement)) {
    collectNamedRuntimeExport(statement, state, typeIndex);
    return;
  }

  if (ts.isVariableStatement(statement)) {
    collectVariableExports(statement, state, typeIndex);
    return;
  }

  if (ts.isExportAssignment(statement)) {
    state.hasRuntimeExports = true;
    addExportEntry(state, buildExportEntry({
      exportedName: 'default',
      declarationKind: 'default',
      runtimeKind: describeNodeKind(statement.expression),
      functionInfo: analyzeRuntimeFunction(statement.expression, typeIndex),
      localName: readLocalName(statement.expression)
    }));
    return;
  }

  if (ts.isExportDeclaration(statement)) {
    collectExportDeclaration(statement, state);
    return;
  }

  if (ts.isExpressionStatement(statement)) {
    collectCommonJsExports(statement.expression, state, typeIndex);
  }
}

function collectNamedRuntimeExport(statement, state, typeIndex) {
  if (!hasModifier(statement, ts.SyntaxKind.ExportKeyword)) {
    return;
  }

  state.hasRuntimeExports = true;
  const declarationKind = ts.isClassDeclaration(statement)
    ? 'class'
    : ts.isEnumDeclaration(statement)
      ? 'enum'
      : 'function';
  const runtimeKind = declarationKind === 'enum' ? 'object' : declarationKind;
  const exportedName = hasModifier(statement, ts.SyntaxKind.DefaultKeyword)
    ? 'default'
    : statement.name
      ? statement.name.text
      : null;

  if (!exportedName) {
    state.exactExports = false;
    return;
  }

  addExportEntry(state, buildExportEntry({
    exportedName,
    declarationKind,
    runtimeKind,
    functionInfo: analyzeRuntimeFunction(statement, typeIndex),
    localName: statement.name ? statement.name.text : null
  }));
}

function collectVariableExports(statement, state, typeIndex) {
  if (!hasModifier(statement, ts.SyntaxKind.ExportKeyword)) {
    return;
  }

  state.hasRuntimeExports = true;

  for (const declaration of statement.declarationList.declarations) {
    if (!ts.isIdentifier(declaration.name)) {
      state.exactExports = false;
      continue;
    }

    addExportEntry(state, buildExportEntry({
      exportedName: declaration.name.text,
      declarationKind: 'variable',
      runtimeKind: describeNodeKind(declaration.initializer),
      functionInfo: analyzeRuntimeFunction(declaration.initializer, typeIndex),
      localName: declaration.name.text
    }));
  }
}

function collectExportDeclaration(statement, state) {
  if (statement.isTypeOnly) {
    return;
  }

  state.hasRuntimeExports = true;

  if (!statement.exportClause) {
    state.exactExports = false;
    return;
  }

  if (ts.isNamedExports(statement.exportClause)) {
    for (const element of statement.exportClause.elements) {
      if (element.isTypeOnly) {
        continue;
      }

      addExportEntry(state, buildExportEntry({
        exportedName: element.name.text,
        declarationKind: 'reexport',
        runtimeKind: 'unknown',
        functionInfo: null,
        localName: element.propertyName ? element.propertyName.text : element.name.text
      }));
    }
    return;
  }

  state.exactExports = false;
}

function collectCommonJsExports(expression, state, typeIndex) {
  if (!ts.isBinaryExpression(expression) || expression.operatorToken.kind !== ts.SyntaxKind.EqualsToken) {
    return;
  }

  const { left, right } = expression;

  if (isModuleExportsReference(left)) {
    state.hasRuntimeExports = true;

    if (ts.isObjectLiteralExpression(right)) {
      const names = readObjectLiteralExportEntries(right, typeIndex);
      if (!names) {
        state.exactExports = false;
        return;
      }

      for (const entry of names) {
        addExportEntry(state, entry);
      }
      return;
    }

    addExportEntry(state, buildExportEntry({
      exportedName: 'default',
      declarationKind: 'commonjs',
      runtimeKind: describeNodeKind(right),
      functionInfo: analyzeRuntimeFunction(right, typeIndex),
      localName: readLocalName(right)
    }));
    return;
  }

  const namedExport = resolveCommonJsNamedExport(left);
  if (!namedExport) {
    return;
  }

  state.hasRuntimeExports = true;
  addExportEntry(state, buildExportEntry({
    exportedName: namedExport,
    declarationKind: 'commonjs',
    runtimeKind: describeNodeKind(right),
    functionInfo: analyzeRuntimeFunction(right, typeIndex),
    localName: readLocalName(right)
  }));
}

function analyzeRuntimeFunction(node, typeIndex) {
  if (!node) {
    return null;
  }

  if (
    ts.isFunctionDeclaration(node)
    || ts.isFunctionExpression(node)
    || ts.isArrowFunction(node)
    || ts.isMethodDeclaration(node)
    || ts.isGetAccessorDeclaration(node)
    || ts.isSetAccessorDeclaration(node)
  ) {
    return analyzeFunctionLike(node, typeIndex);
  }

  if (ts.isClassDeclaration(node) || ts.isClassExpression(node)) {
    const constructorDeclaration = node.members.find((member) => ts.isConstructorDeclaration(member));
    return {
      async: false,
      parameterCount: constructorDeclaration ? constructorDeclaration.parameters.length : 0,
      parameters: constructorDeclaration ? constructorDeclaration.parameters.map((parameter, index) => analyzeParameter(parameter, typeIndex, index)) : [],
      usesJsx: false,
      classLike: true
    };
  }

  return null;
}

function analyzeFunctionLike(node, typeIndex) {
  return {
    async: hasModifier(node, ts.SyntaxKind.AsyncKeyword),
    parameterCount: node.parameters.length,
    parameters: node.parameters.map((parameter, index) => analyzeParameter(parameter, typeIndex, index)),
    usesJsx: containsJsx(node.body || node)
  };
}

function analyzeParameter(parameter, typeIndex, index) {
  const typeDescriptor = resolveTypeDescriptor(parameter.type, typeIndex);
  const bindingKind = ts.isObjectBindingPattern(parameter.name)
    ? 'object'
    : ts.isArrayBindingPattern(parameter.name)
      ? 'array'
      : 'identifier';
  const name = readBindingName(parameter.name, index);
  const objectFields = ts.isObjectBindingPattern(parameter.name)
    ? readBindingPatternFields(parameter.name, typeDescriptor.objectFields || [])
    : typeDescriptor.objectFields || [];

  return {
    name,
    bindingKind,
    optional: Boolean(parameter.questionToken),
    hasDefault: Boolean(parameter.initializer),
    defaultValue: parameter.initializer ? serializeLiteralNode(parameter.initializer) : undefined,
    inferredType: typeDescriptor.inferredType,
    sampleValue: typeDescriptor.sampleValue,
    objectFields
  };
}

function readBindingPatternFields(pattern, typeFields) {
  const typeFieldMap = new Map(typeFields.map((field) => [field.name, field]));
  const fields = [];

  for (const element of pattern.elements) {
    if (ts.isOmittedExpression(element)) {
      continue;
    }

    const propertyName = element.propertyName ? getPropertyName(element.propertyName) : getPropertyName(element.name);
    const fieldName = propertyName || getPropertyName(element.name);
    const typeField = typeFieldMap.get(fieldName) || null;

    fields.push({
      name: fieldName,
      optional: Boolean(element.questionToken) || Boolean(typeField && typeField.optional),
      sampleValue: element.initializer
        ? serializeLiteralNode(element.initializer)
        : typeField
          ? cloneSerializable(typeField.sampleValue)
          : undefined,
      inferredType: typeField ? typeField.inferredType : 'unknown'
    });
  }

  for (const field of typeFields) {
    if (!fields.some((candidate) => candidate.name === field.name)) {
      fields.push({
        name: field.name,
        optional: field.optional,
        sampleValue: cloneSerializable(field.sampleValue),
        inferredType: field.inferredType
      });
    }
  }

  return fields;
}

function containsJsx(node) {
  let found = false;

  walkNode(node, (current) => {
    if (
      ts.isJsxElement(current)
      || ts.isJsxSelfClosingElement(current)
      || ts.isJsxFragment(current)
    ) {
      found = true;
      return true;
    }
    return false;
  });

  return found;
}

function walkNode(node, visit) {
  if (!node || visit(node) === true) {
    return;
  }

  ts.forEachChild(node, (child) => {
    walkNode(child, visit);
  });
}

function buildExportEntry(entry) {
  return {
    exportedName: entry.exportedName,
    declarationKind: entry.declarationKind,
    runtimeKind: entry.runtimeKind || 'unknown',
    functionInfo: entry.functionInfo || null,
    localName: entry.localName || null
  };
}

function describeNodeKind(node) {
  if (!node) {
    return 'unknown';
  }
  if (
    ts.isFunctionDeclaration(node)
    || ts.isFunctionExpression(node)
    || ts.isArrowFunction(node)
    || ts.isMethodDeclaration(node)
  ) {
    return 'function';
  }
  if (ts.isClassDeclaration(node) || ts.isClassExpression(node)) {
    return 'class';
  }
  if (ts.isObjectLiteralExpression(node)) {
    return 'object';
  }
  if (ts.isArrayLiteralExpression(node)) {
    return 'array';
  }
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return 'string';
  }
  if (ts.isNumericLiteral(node)) {
    return 'number';
  }
  if (node.kind === ts.SyntaxKind.TrueKeyword || node.kind === ts.SyntaxKind.FalseKeyword) {
    return 'boolean';
  }
  return 'unknown';
}

function readLocalName(node) {
  if (!node) {
    return null;
  }

  if (ts.isIdentifier(node)) {
    return node.text;
  }
  if ((ts.isFunctionDeclaration(node) || ts.isFunctionExpression(node) || ts.isClassDeclaration(node) || ts.isClassExpression(node)) && node.name) {
    return node.name.text;
  }
  return null;
}

function hasModifier(node, kind) {
  return Array.isArray(node.modifiers) && node.modifiers.some((modifier) => modifier.kind === kind);
}

function isModuleExportsReference(node) {
  return ts.isPropertyAccessExpression(node)
    && ts.isIdentifier(node.expression)
    && node.expression.text === 'module'
    && node.name.text === 'exports';
}

function resolveCommonJsNamedExport(node) {
  const directExports = readExportsMemberName(node);
  if (directExports && directExports !== '__esModule') {
    return directExports;
  }

  if (ts.isPropertyAccessExpression(node) && isModuleExportsReference(node.expression)) {
    return node.name.text === '__esModule' ? null : node.name.text;
  }

  if (ts.isElementAccessExpression(node) && isModuleExportsReference(node.expression)) {
    return readKnownPropertyName(node.argumentExpression);
  }

  return null;
}

function readExportsMemberName(node) {
  if (ts.isPropertyAccessExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === 'exports') {
    return node.name.text;
  }

  if (ts.isElementAccessExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === 'exports') {
    return readKnownPropertyName(node.argumentExpression);
  }

  return null;
}

function readKnownPropertyName(node) {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return node.text === '__esModule' ? null : node.text;
  }
  return null;
}

function readModuleSpecifier(node) {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return node.text;
  }
  return null;
}

function readObjectLiteralExportEntries(node, typeIndex) {
  const entries = [];

  for (const property of node.properties) {
    if (ts.isSpreadAssignment(property)) {
      return null;
    }

    if (ts.isShorthandPropertyAssignment(property)) {
      entries.push(buildExportEntry({
        exportedName: property.name.text,
        declarationKind: 'commonjs',
        runtimeKind: 'unknown',
        functionInfo: null,
        localName: property.name.text
      }));
      continue;
    }

    if (
      ts.isPropertyAssignment(property)
      || ts.isMethodDeclaration(property)
      || ts.isGetAccessorDeclaration(property)
      || ts.isSetAccessorDeclaration(property)
    ) {
      const propertyName = getPropertyName(property.name);
      if (!propertyName) {
        return null;
      }

      const valueNode = ts.isPropertyAssignment(property) ? property.initializer : property;
      entries.push(buildExportEntry({
        exportedName: propertyName,
        declarationKind: 'commonjs',
        runtimeKind: describeNodeKind(valueNode),
        functionInfo: analyzeRuntimeFunction(valueNode, typeIndex),
        localName: propertyName
      }));
      continue;
    }

    return null;
  }

  return entries.filter((entry) => entry.exportedName !== '__esModule');
}

function getPropertyName(node) {
  if (ts.isIdentifier(node) || ts.isStringLiteral(node) || ts.isNumericLiteral(node)) {
    return node.text;
  }
  return null;
}

function addExportEntry(state, entry) {
  if (!entry || !entry.exportedName || entry.exportedName === '__esModule') {
    return;
  }

  state.exportNames.add(entry.exportedName);
  state.exportMap.set(entry.exportedName, entry);
}

function applyHintExportFilters(analysis) {
  const hints = analysis.hints;
  if (!hints) {
    return;
  }

  let entries = analysis.exportEntries;
  if (Array.isArray(hints.includeExports) && hints.includeExports.length > 0) {
    const includeSet = new Set(hints.includeExports);
    entries = entries.filter((entry) => includeSet.has(entry.exportedName));
  }
  if (Array.isArray(hints.excludeExports) && hints.excludeExports.length > 0) {
    const excludeSet = new Set(hints.excludeExports);
    entries = entries.filter((entry) => !excludeSet.has(entry.exportedName));
  }

  analysis.exportEntries = entries;
  analysis.exportNames = entries.map((entry) => entry.exportedName).sort();
  analysis.hasRuntimeExports = entries.length > 0;
  if (!analysis.hasRuntimeExports) {
    analysis.skipReason = 'Runtime exports were filtered out by hint configuration.';
  }
}

function matchesExportFilter(analysis, matchExport) {
  return analysis.exportNames.some((name) => matchExport.test(name));
}

function resolveScenarioPlans(analysis) {
  const scenarios = [];
  scenarios.push(buildModuleContractScenario(analysis));

  const reactComponents = resolveReactComponentCases(analysis);
  if (reactComponents.length > 0) {
    scenarios.push({
      kind: 'react-component',
      confidence: pickHighestConfidence(reactComponents.map((entry) => entry.confidence)),
      exports: reactComponents.map((entry) => entry.exportName),
      cases: reactComponents
    });
  }

  const reactHooks = resolveReactHookCases(analysis);
  if (reactHooks.length > 0) {
    scenarios.push({
      kind: 'react-hook',
      confidence: pickHighestConfidence(reactHooks.map((entry) => entry.confidence)),
      exports: reactHooks.map((entry) => entry.exportName),
      cases: reactHooks
    });
  }

  const routeHandlers = resolveRouteCases(analysis);
  if (routeHandlers.length > 0) {
    scenarios.push({
      kind: 'route-handler',
      confidence: pickHighestConfidence(routeHandlers.map((entry) => entry.confidence)),
      exports: routeHandlers.map((entry) => entry.exportName),
      cases: routeHandlers
    });
  }

  const nodeServices = resolveNodeServiceCases(analysis, scenarios);
  if (nodeServices.length > 0) {
    scenarios.push({
      kind: 'node-service',
      confidence: pickHighestConfidence(nodeServices.map((entry) => entry.confidence)),
      exports: nodeServices.map((entry) => entry.exportName),
      cases: nodeServices
    });
  }

  return scenarios.sort((a, b) => SCENARIO_PRIORITY.indexOf(a.kind) - SCENARIO_PRIORITY.indexOf(b.kind));
}

function buildModuleContractScenario(analysis) {
  return {
    kind: 'module-contract',
    confidence: analysis.exactExports ? 'medium' : 'low',
    exports: [...analysis.exportNames],
    cases: []
  };
}

function resolveReactComponentCases(analysis) {
  const forced = hasScenarioHint(analysis, 'react-component');
  const cases = [];

  for (const entry of analysis.exportEntries) {
    if (!entry.functionInfo && entry.runtimeKind !== 'class') {
      continue;
    }

    const looksLikeComponent = forced
      || (analysis.usesJsx || analysis.importsReact)
      && !isHookName(entry.exportedName)
      && isPascalCase(resolveDisplayExportName(analysis, entry))
      && (entry.functionInfo ? entry.functionInfo.usesJsx || analysis.usesJsx : true);

    if (!looksLikeComponent) {
      continue;
    }

    const propsSamples = resolveComponentPropsSamples(analysis, entry);
    cases.push({
      exportName: entry.exportedName,
      displayName: resolveDisplayExportName(analysis, entry),
      caseName: propsSamples.hinted ? 'renders with hinted props' : 'renders with inferred props',
      props: propsSamples.props,
      confidence: propsSamples.confidence
    });
  }

  return cases;
}

function resolveReactHookCases(analysis) {
  const forced = hasScenarioHint(analysis, 'react-hook');
  const cases = [];

  for (const entry of analysis.exportEntries) {
    if (!entry.functionInfo) {
      continue;
    }

    if (!forced && !isHookName(resolveDisplayExportName(analysis, entry))) {
      continue;
    }

    const argsSamples = resolveArgsSamples(analysis, entry, 'hookArgs');
    cases.push({
      exportName: entry.exportedName,
      displayName: resolveDisplayExportName(analysis, entry),
      caseName: argsSamples.hinted ? 'returns a hinted hook contract' : 'returns an inferred hook contract',
      args: argsSamples.args,
      confidence: argsSamples.confidence
    });
  }

  return cases;
}

function resolveRouteCases(analysis) {
  const forced = hasScenarioHint(analysis, 'route-handler');
  const cases = [];

  for (const entry of analysis.exportEntries) {
    if (!entry.functionInfo) {
      continue;
    }

    const looksLikeRoute = forced
      || HTTP_METHOD_EXPORTS.includes(entry.exportedName)
      || isRouteFile(analysis.file) && entry.exportedName === 'default';

    if (!looksLikeRoute) {
      continue;
    }

    const requestHints = resolveHintCollection(analysis.hints, 'routeRequests', entry.exportedName);
    const contextHints = resolveHintCollection(analysis.hints, 'routeContext', entry.exportedName);
    const request = normalizeRouteRequestHint(requestHints, entry.exportedName, analysis.relativeFile);
    const context = normalizeRouteContextHint(contextHints);

    cases.push({
      exportName: entry.exportedName,
      displayName: resolveDisplayExportName(analysis, entry),
      caseName: requestHints ? 'returns a hinted response contract' : 'returns an inferred response contract',
      request,
      context,
      confidence: requestHints ? 'high' : 'medium'
    });
  }

  return cases;
}

function resolveNodeServiceCases(analysis, existingScenarios) {
  const reservedExports = new Set();
  for (const scenario of existingScenarios) {
    if (scenario.kind === 'module-contract') {
      continue;
    }
    for (const exportName of scenario.exports) {
      reservedExports.add(exportName);
    }
  }

  const forced = hasScenarioHint(analysis, 'node-service');
  const cases = [];

  for (const entry of analysis.exportEntries) {
    if (!entry.functionInfo || reservedExports.has(entry.exportedName)) {
      continue;
    }

    if (!forced && entry.runtimeKind !== 'function') {
      continue;
    }

    const argsSamples = resolveArgsSamples(analysis, entry, 'serviceArgs');
    cases.push({
      exportName: entry.exportedName,
      displayName: resolveDisplayExportName(analysis, entry),
      caseName: argsSamples.hinted ? 'returns a hinted invocation contract' : 'returns an inferred invocation contract',
      args: argsSamples.args,
      confidence: argsSamples.confidence
    });
  }

  return cases;
}

function resolveComponentPropsSamples(analysis, entry) {
  const hinted = resolveHintCollection(analysis.hints, 'componentProps', entry.exportedName);
  if (hinted) {
    const props = Array.isArray(hinted) ? hinted[0] : hinted;
    return {
      props: cloneSerializable(props) || {},
      hinted: true,
      confidence: 'high'
    };
  }

  const functionInfo = entry.functionInfo || { parameters: [] };
  const firstParameter = functionInfo.parameters[0];
  if (!firstParameter) {
    return { props: {}, hinted: false, confidence: 'medium' };
  }

  if (firstParameter.bindingKind === 'object') {
    return {
      props: buildObjectSample(firstParameter.objectFields),
      hinted: false,
      confidence: 'medium'
    };
  }

  if (firstParameter.sampleValue && isPlainObject(firstParameter.sampleValue)) {
    return {
      props: cloneSerializable(firstParameter.sampleValue),
      hinted: false,
      confidence: 'medium'
    };
  }

  return {
    props: {},
    hinted: false,
    confidence: 'low'
  };
}

function resolveArgsSamples(analysis, entry, hintKey) {
  const hinted = resolveHintCollection(analysis.hints, hintKey, entry.exportedName);
  if (hinted) {
    const args = Array.isArray(hinted) && Array.isArray(hinted[0]) ? hinted[0] : Array.isArray(hinted) ? hinted : [hinted];
    return {
      args: cloneSerializable(args),
      hinted: true,
      confidence: 'high'
    };
  }

  const functionInfo = entry.functionInfo || { parameters: [] };
  const args = functionInfo.parameters.map((parameter, index) => inferSampleFromParameter(parameter, entry, index));
  return {
    args,
    hinted: false,
    confidence: args.length === 0 ? 'medium' : 'low'
  };
}

function inferSampleFromParameter(parameter, entry, index) {
  if (parameter.defaultValue !== undefined) {
    return cloneSerializable(parameter.defaultValue);
  }

  if (parameter.bindingKind === 'object') {
    return buildObjectSample(parameter.objectFields);
  }

  if (parameter.sampleValue !== undefined) {
    return cloneSerializable(parameter.sampleValue);
  }

  const lowerName = String(parameter.name || '').toLowerCase();
  const entryName = String(entry.localName || entry.exportedName || '').toLowerCase();

  if (
    parameter.inferredType === 'number'
    || /(count|size|total|limit|offset|page|index|amount|id)$/.test(lowerName)
    || /(add|subtract|multiply|divide|sum|total|count)/.test(entryName)
  ) {
    return index + 1;
  }

  if (parameter.inferredType === 'boolean' || /^(is|has|can|should|enabled|disabled)/.test(lowerName)) {
    return false;
  }

  if (parameter.inferredType === 'array') {
    return [];
  }

  if (parameter.inferredType === 'object' || /(options|config|params|payload|input|props|context)$/.test(lowerName)) {
    return {};
  }

  if (/(url|href|uri)/.test(lowerName)) {
    return 'https://themis.test';
  }

  if (lowerName === 'children') {
    return 'Themis child';
  }

  return index === 0 ? 'themis' : `themis-${index + 1}`;
}

function buildObjectSample(fields) {
  const sample = {};

  for (const field of fields || []) {
    const inferred = field.sampleValue !== undefined
      ? cloneSerializable(field.sampleValue)
      : inferFieldFallback(field.name, field.inferredType);
    sample[field.name] = inferred;
  }

  return sample;
}

function inferFieldFallback(name, inferredType) {
  const lowerName = String(name || '').toLowerCase();

  if (inferredType === 'number' || /(count|size|total|limit|offset|page|index|amount|id)$/.test(lowerName)) {
    return 1;
  }
  if (inferredType === 'boolean' || /^(is|has|can|should|enabled|disabled)/.test(lowerName)) {
    return false;
  }
  if (inferredType === 'array') {
    return [];
  }
  if (inferredType === 'object' || /(options|config|params|payload|input|props|context)$/.test(lowerName)) {
    return {};
  }
  if (lowerName === 'children') {
    return 'Themis child';
  }
  return 'themis';
}

function hasScenarioHint(analysis, scenarioName) {
  const scenarios = analysis.hints && analysis.hints.scenarios;
  return Array.isArray(scenarios) && scenarios.includes(scenarioName);
}

function resolveHintCollection(hints, key, exportName) {
  if (!hints || !hints[key]) {
    return null;
  }

  const value = hints[key];
  if (Array.isArray(value)) {
    return value;
  }
  if (isPlainObject(value)) {
    if (Object.prototype.hasOwnProperty.call(value, exportName)) {
      return value[exportName];
    }
    if (Object.prototype.hasOwnProperty.call(value, 'default')) {
      return value.default;
    }
  }
  return value;
}

function normalizeRouteRequestHint(value, exportName, relativeFile) {
  if (value) {
    const hint = Array.isArray(value) ? value[0] : value;
    return {
      method: hint.method || exportName || 'GET',
      url: hint.url || `https://themis.test/${relativeFile.replace(/^src\//, '').replace(/\.(jsx?|tsx?)$/, '')}`,
      headers: cloneSerializable(hint.headers) || {},
      body: hint.body,
      json: cloneSerializable(hint.json)
    };
  }

  return {
    method: exportName || 'GET',
    url: `https://themis.test/${relativeFile.replace(/^src\//, '').replace(/\.(jsx?|tsx?)$/, '')}`,
    headers: {},
    body: undefined,
    json: undefined
  };
}

function normalizeRouteContextHint(value) {
  if (!value) {
    return { params: {} };
  }

  const hint = Array.isArray(value) ? value[0] : value;
  return cloneSerializable(hint) || { params: {} };
}

function resolveDisplayExportName(analysis, entry) {
  if (entry.exportedName !== 'default') {
    return entry.exportedName;
  }

  if (entry.localName) {
    return entry.localName;
  }

  const basename = path.parse(analysis.file).name;
  return basename.charAt(0).toUpperCase() + basename.slice(1);
}

function isHookName(name) {
  return /^use[A-Z]/.test(name);
}

function isPascalCase(name) {
  return /^[A-Z][A-Za-z0-9]*$/.test(name);
}

function isRouteFile(filePath) {
  const basename = path.parse(filePath).name.toLowerCase();
  return basename === 'route' || basename.endsWith('route') || basename.endsWith('handler');
}

function pickPrimaryScenario(scenarios) {
  for (const scenarioName of SCENARIO_PRIORITY) {
    const scenario = scenarios.find((candidate) => candidate.kind === scenarioName);
    if (scenario) {
      return scenario.kind;
    }
  }
  return 'module-contract';
}

function pickOverallConfidence(scenarios) {
  const confidences = scenarios.map((scenario) => scenario.confidence);
  return pickHighestConfidence(confidences);
}

function pickHighestConfidence(confidences) {
  let current = 'low';

  for (const confidence of confidences) {
    if (CONFIDENCE_PRIORITY.indexOf(confidence) > CONFIDENCE_PRIORITY.indexOf(current)) {
      current = confidence;
    }
  }

  return current;
}

function readHintFile(filePath) {
  const hintPath = resolveHintFilePath(filePath);
  if (!fs.existsSync(hintPath)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(hintPath, 'utf8'));
  } catch (error) {
    throw new Error(`Failed to parse Themis hint file ${hintPath}: ${error.message}`);
  }
}

function resolveHintFilePath(filePath) {
  const parsed = path.parse(filePath);
  return path.join(parsed.dir, `${parsed.name}${HINT_FILE_SUFFIX}`);
}

function buildPlan(analysis, content, action, existing, projectRoot) {
  return {
    action,
    content,
    outputFile: analysis.outputFile,
    sourceFile: analysis.file,
    sourceHash: analysis.sourceHash,
    moduleKind: analysis.moduleKind,
    confidence: analysis.confidence,
    exactExports: analysis.exactExports,
    exportNames: [...analysis.exportNames],
    hintsFile: analysis.hintsFile,
    scenarios: analysis.scenarios.map((scenario) => ({
      kind: scenario.kind,
      confidence: scenario.confidence,
      exports: [...scenario.exports],
      caseCount: Array.isArray(scenario.cases) ? scenario.cases.length : 0
    })),
    entry: buildGenerateMapEntry(analysis, existing, projectRoot)
  };
}

function buildConflictPlan(analysis, content, action, projectRoot) {
  return {
    action: 'conflict',
    content,
    outputFile: analysis.outputFile,
    sourceFile: analysis.file,
    sourceHash: analysis.sourceHash,
    moduleKind: analysis.moduleKind,
    confidence: analysis.confidence,
    exactExports: analysis.exactExports,
    exportNames: [...analysis.exportNames],
    hintsFile: analysis.hintsFile,
    reason: 'Conflicting non-Themis file requires --force.',
    scenarios: analysis.scenarios.map((scenario) => ({
      kind: scenario.kind,
      confidence: scenario.confidence,
      exports: [...scenario.exports],
      caseCount: Array.isArray(scenario.cases) ? scenario.cases.length : 0
    })),
    entry: buildGenerateMapEntry(analysis, null, projectRoot)
  };
}

function buildGenerateMapEntry(analysis, existing, projectRoot) {
  return {
    sourceKey: safeRealpath(analysis.file),
    sourceFile: formatPathForDisplay(projectRoot, analysis.file),
    sourceHash: analysis.sourceHash,
    testFile: formatPathForDisplay(projectRoot, analysis.outputFile),
    moduleKind: analysis.moduleKind,
    confidence: analysis.confidence,
    exactExports: analysis.exactExports,
    exportNames: [...analysis.exportNames],
    hintsFile: analysis.hintsFile,
    scenarios: analysis.scenarios.map((scenario) => ({
      kind: scenario.kind,
      confidence: scenario.confidence,
      exports: [...scenario.exports],
      caseCount: Array.isArray(scenario.cases) ? scenario.cases.length : 0
    })),
    previousTestFile: existing ? existing.testFile : null
  };
}

function resolveCleanTargets({ analyses, existingMap, projectRoot, selectedSourceKeys, hasSelectionFilters, changedSet }) {
  const targets = [];
  const analysisKeys = new Set(analyses.map((analysis) => safeRealpath(analysis.file)));

  for (const entry of existingMap.entries) {
    const entryKey = entry.sourceKey;
    const shouldRemove = hasSelectionFilters
      ? selectedSourceKeys.has(entryKey) || analysisKeys.has(entryKey) || Boolean(changedSet && changedSet.has(entryKey))
      : true;

    if (!shouldRemove) {
      continue;
    }

    targets.push({
      sourceKey: entryKey,
      sourceFile: path.resolve(projectRoot, entry.sourceFile),
      file: path.resolve(projectRoot, entry.testFile),
      reason: 'Clean mode removed generated test.'
    });
  }

  return targets;
}

function mergeGenerateMapEntries({ existingEntries, plans, removedPlans, review, clean, projectRoot }) {
  const merged = new Map();

  for (const entry of existingEntries) {
    merged.set(entry.sourceKey, { ...entry });
  }

  for (const removedPlan of removedPlans) {
    merged.delete(removedPlan.sourceKey);
  }

  if (clean) {
    return [...merged.values()];
  }

  for (const plan of plans) {
    if (plan.action === 'conflict') {
      continue;
    }

    const sourceKey = safeRealpath(plan.sourceFile);
    const existing = merged.get(sourceKey);
    merged.set(sourceKey, {
      ...plan.entry,
      sourceKey,
      sourceFile: formatPathForDisplay(projectRoot, plan.sourceFile),
      testFile: formatPathForDisplay(projectRoot, plan.outputFile),
      previousTestFile: existing ? existing.testFile : null
    });
  }

  if (review) {
    return [...merged.values()];
  }

  return [...merged.values()].sort((a, b) => a.sourceFile.localeCompare(b.sourceFile));
}

function writeGenerateMap(mapFile, projectRoot, scanTarget, outputDir, entries) {
  fs.mkdirSync(path.dirname(mapFile), { recursive: true });

  const payload = {
    schema: 'themis.generate.map.v1',
    generatedAt: new Date().toISOString(),
    targetDir: formatPathForDisplay(projectRoot, scanTarget.requestedPath),
    outputDir: formatPathForDisplay(projectRoot, outputDir),
    entries: entries.map((entry) => ({
      sourceFile: formatPathForDisplay(projectRoot, path.resolve(projectRoot, entry.sourceFile)),
      sourceHash: entry.sourceHash,
      testFile: formatPathForDisplay(projectRoot, path.resolve(projectRoot, entry.testFile)),
      moduleKind: entry.moduleKind,
      confidence: entry.confidence,
      exactExports: entry.exactExports,
      exportNames: entry.exportNames,
      hintsFile: entry.hintsFile ? formatPathForDisplay(projectRoot, entry.hintsFile) : null,
      scenarios: entry.scenarios
    }))
  };

  fs.writeFileSync(mapFile, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
}

function readGenerateMap(mapFile, projectRoot) {
  if (!fs.existsSync(mapFile)) {
    return { entries: [] };
  }

  try {
    const payload = JSON.parse(fs.readFileSync(mapFile, 'utf8'));
    const entries = Array.isArray(payload.entries) ? payload.entries.map((entry) => ({
      sourceKey: safeRealpath(path.resolve(projectRoot, entry.sourceFile)),
      sourceFile: entry.sourceFile,
      sourceHash: entry.sourceHash,
      testFile: entry.testFile,
      moduleKind: entry.moduleKind,
      confidence: entry.confidence,
      exactExports: entry.exactExports,
      exportNames: entry.exportNames,
      hintsFile: entry.hintsFile ? path.resolve(projectRoot, entry.hintsFile) : null,
      scenarios: entry.scenarios || []
    })) : [];
    return { entries };
  } catch (error) {
    throw new Error(`Failed to parse generate map artifact at ${mapFile}: ${error.message}`);
  }
}

function removeGenerateMap(mapFile) {
  if (fs.existsSync(mapFile)) {
    fs.rmSync(mapFile, { force: true });
    pruneEmptyDirectories(path.dirname(mapFile), path.dirname(mapFile));
  }
}

function buildSummaryEntries({ plans, removedPlans, projectRoot, review }) {
  const entries = [];

  for (const plan of plans) {
    entries.push({
      action: plan.action,
      sourceFile: plan.sourceFile,
      testFile: plan.outputFile,
      moduleKind: plan.moduleKind,
      confidence: plan.confidence,
      exactExports: plan.exactExports,
      exportNames: plan.exportNames,
      hintsFile: plan.hintsFile,
      sourceHash: plan.sourceHash,
      scenarios: plan.scenarios,
      reason: plan.reason || null,
      review
    });
  }

  for (const removedPlan of removedPlans) {
    entries.push({
      action: 'remove',
      sourceFile: removedPlan.sourceFile || removedPlan.file,
      testFile: removedPlan.file,
      moduleKind: 'module-contract',
      confidence: 'low',
      exactExports: false,
      exportNames: [],
      hintsFile: null,
      sourceHash: null,
      scenarios: [],
      reason: removedPlan.reason || null,
      review
    });
  }

  return entries.sort((a, b) => String(a.testFile || '').localeCompare(String(b.testFile || '')));
}

function buildFilterSummary(options, projectRoot) {
  return {
    plan: Boolean(options.plan),
    changed: options.changed,
    files: options.files ? options.files.map((file) => formatPathForDisplay(projectRoot, file)) : [],
    scenario: options.scenario || null,
    minConfidence: options.minConfidence || null,
    matchSource: options.matchSource ? String(options.matchSource) : null,
    matchExport: options.matchExport ? String(options.matchExport) : null,
    include: options.include ? String(options.include) : null,
    exclude: options.exclude ? String(options.exclude) : null
  };
}

function buildPromptSummary({
  projectRoot,
  plan,
  review,
  update,
  clean,
  createdFiles,
  updatedFiles,
  unchangedFiles,
  removedFiles,
  skippedFiles,
  conflictFiles,
  targetDir
}) {
  const mode = clean ? 'clean' : plan ? 'plan' : review ? 'review' : update ? 'update' : 'generate';
  const target = formatPathForDisplay(projectRoot, targetDir);

  return [
    `Mode: ${mode}.`,
    `Target: ${target}.`,
    `Actions: create ${createdFiles.length}, update ${updatedFiles.length}, unchanged ${unchangedFiles.length}, remove ${removedFiles.length}, skip ${skippedFiles.length}, conflict ${conflictFiles.length}.`,
    review ? `${plan ? 'Plan' : 'Review'} mode made no filesystem changes.` : 'Run npx themis test to validate the generated unit layer.'
  ].join(' ');
}

function buildPromptReadyPayload(summary, projectRoot) {
  const targets = summary.entries
    .filter((entry) => entry.action !== 'remove')
    .map((entry) => ({
      action: entry.action,
      sourceFile: formatPathForDisplay(projectRoot, entry.sourceFile),
      testFile: entry.testFile ? formatPathForDisplay(projectRoot, entry.testFile) : null,
      moduleKind: entry.moduleKind,
      confidence: entry.confidence,
      scenarios: entry.scenarios.map((scenario) => scenario.kind)
    }));

  return {
    summary: summary.prompt,
    targets,
    nextActions: summary.review
      ? [
          'Review planned create/update/remove actions.',
          `Run ${summary.plan ? 'npx themis generate <target>' : 'npx themis generate <target> without --review'} when ready.`,
          'Run npx themis test after generation.'
        ]
      : ['Review generated test diffs.', 'Run npx themis test.', 'Use npx themis generate <file> --update for narrow refreshes.'],
    prompt: [
      'Review the following Themis generation result and act on the mapped source/test pairs.',
      summary.prompt,
      ...targets.map((target) => `- ${target.action.toUpperCase()} ${target.sourceFile} -> ${target.testFile || '(no file)'}`),
      'Then run: npx themis test'
    ].join('\n')
  };
}

function hasTargetedSelection(options, scanTarget) {
  return Boolean(
    scanTarget.isFile
      || options.changed
      || options.plan
      || options.scenario
      || options.minConfidence
      || options.matchSource
      || options.matchExport
      || options.include
      || options.exclude
      || (options.files && options.files.length > 0)
  );
}

function discoverSourceFiles(dir, outputDir, files) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) {
      continue;
    }

    const fullPath = path.join(dir, entry.name);
    if (isSameOrSubPath(fullPath, outputDir)) {
      continue;
    }

    if (entry.isDirectory()) {
      discoverSourceFiles(fullPath, outputDir, files);
      continue;
    }

    if (!entry.isFile() || !isEligibleSourceFile(fullPath)) {
      continue;
    }

    files.push(fullPath);
  }

  files.sort();
}

function isEligibleSourceFile(filePath) {
  const extension = path.extname(filePath).toLowerCase();
  if (!SOURCE_EXTENSIONS.has(extension)) {
    return false;
  }
  if (filePath.endsWith('.d.ts')) {
    return false;
  }
  if (filePath.endsWith(HINT_FILE_SUFFIX)) {
    return false;
  }
  return !TEST_FILE_PATTERN.test(path.basename(filePath));
}

function resolveScriptKind(filePath) {
  const extension = path.extname(filePath).toLowerCase();
  if (extension === '.ts') {
    return ts.ScriptKind.TS;
  }
  if (extension === '.tsx') {
    return ts.ScriptKind.TSX;
  }
  if (extension === '.jsx') {
    return ts.ScriptKind.JSX;
  }
  return ts.ScriptKind.JS;
}

function resolveGeneratedTestPath(outputDir, mirrorBase, sourceFile) {
  const relativeSource = path.relative(mirrorBase, sourceFile);
  const parsed = path.parse(relativeSource);
  return path.join(outputDir, parsed.dir, `${parsed.name}.generated.test.js`);
}

function renderGeneratedTest({ projectRoot, helperFile, outputFile, analysis }) {
  const relativeSourcePath = normalizePath(path.relative(projectRoot, analysis.file));
  const helperImport = normalizeRelativeModule(path.relative(path.dirname(outputFile), helperFile));
  const sourceImport = normalizeRelativeModule(path.relative(path.dirname(outputFile), analysis.file));
  const sourceAbsolutePath = normalizePath(path.relative(path.dirname(outputFile), analysis.file));
  const suiteName = `generated contract > ${relativeSourcePath}`;
  const exactExportBlock = analysis.exactExports
    ? `test('matches scanned export names', () => {\n    const moduleExports = loadModuleExports();\n    expect(listExportNames(moduleExports)).toEqual(SCANNED_EXPORTS);\n  });`
    : `test('exposes runtime exports after scan', () => {\n    const moduleExports = loadModuleExports();\n    expect(listExportNames(moduleExports).length).toBeTruthy();\n  });`;

  return `${GENERATED_MARKER}
// Source: ${relativeSourcePath}

const path = require('path');
const {
  listExportNames,
  buildModuleContract,
  readExportValue,
  normalizeBehaviorValue,
  normalizeRouteResult,
  createRequestFromSpec,
  assertSourceFreshness
} = require(${JSON.stringify(helperImport)});

const SOURCE_PATH = ${JSON.stringify(relativeSourcePath)};
const SOURCE_IMPORT = ${JSON.stringify(sourceImport)};
const SOURCE_FILE = path.resolve(__dirname, ${JSON.stringify(sourceAbsolutePath)});
const SOURCE_HASH = ${JSON.stringify(analysis.sourceHash)};
const REGENERATE_COMMAND = ${JSON.stringify(`npx themis generate ${relativeSourcePath}`)};
const SCANNED_EXPORTS = ${analysis.exactExports ? JSON.stringify(analysis.exportNames, null, 2) : 'null'};
const COMPONENT_CASES = ${JSON.stringify(flattenScenarioCases(analysis.scenarios, 'react-component'), null, 2)};
const HOOK_CASES = ${JSON.stringify(flattenScenarioCases(analysis.scenarios, 'react-hook'), null, 2)};
const ROUTE_CASES = ${JSON.stringify(flattenScenarioCases(analysis.scenarios, 'route-handler'), null, 2)};
const SERVICE_CASES = ${JSON.stringify(flattenScenarioCases(analysis.scenarios, 'node-service'), null, 2)};

function loadModuleExports() {
  assertSourceFreshness(SOURCE_FILE, SOURCE_HASH, SOURCE_PATH, REGENERATE_COMMAND);
  const resolved = require.resolve(SOURCE_IMPORT);
  delete require.cache[resolved];
  return require(SOURCE_IMPORT);
}

describe(${JSON.stringify(suiteName)}, () => {
  ${exactExportBlock}

  test('captures runtime export contract', () => {
    const moduleExports = loadModuleExports();
    expect({
      source: SOURCE_PATH,
      scannedExports: SCANNED_EXPORTS,
      runtime: buildModuleContract(moduleExports)
    }).toMatchSnapshot();
  });

  if (COMPONENT_CASES.length > 0) {
    describe('react component adapter', () => {
      for (const testCase of COMPONENT_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, () => {
          const moduleExports = loadModuleExports();
          const component = readExportValue(moduleExports, testCase.exportName);
          const rendered = component(testCase.props);
          expect({
            source: SOURCE_PATH,
            scenario: 'react-component',
            confidence: testCase.confidence,
            exportName: testCase.exportName,
            props: testCase.props,
            rendered: normalizeBehaviorValue(rendered)
          }).toMatchSnapshot();
        });
      }
    });
  }

  if (HOOK_CASES.length > 0) {
    describe('react hook adapter', () => {
      for (const testCase of HOOK_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, () => {
          const moduleExports = loadModuleExports();
          const hook = readExportValue(moduleExports, testCase.exportName);
          const result = hook(...testCase.args);
          expect({
            source: SOURCE_PATH,
            scenario: 'react-hook',
            confidence: testCase.confidence,
            exportName: testCase.exportName,
            args: testCase.args,
            result: normalizeBehaviorValue(result)
          }).toMatchSnapshot();
        });
      }
    });
  }

  if (ROUTE_CASES.length > 0) {
    describe('route handler adapter', () => {
      for (const testCase of ROUTE_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, async () => {
          const moduleExports = loadModuleExports();
          const handler = readExportValue(moduleExports, testCase.exportName);
          const request = createRequestFromSpec(testCase.request);
          const response = await Promise.resolve(handler(request, testCase.context));
          expect({
            source: SOURCE_PATH,
            scenario: 'route-handler',
            confidence: testCase.confidence,
            exportName: testCase.exportName,
            request: testCase.request,
            context: testCase.context,
            response: await normalizeRouteResult(response)
          }).toMatchSnapshot();
        });
      }
    });
  }

  if (SERVICE_CASES.length > 0) {
    describe('node service adapter', () => {
      for (const testCase of SERVICE_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, async () => {
          const moduleExports = loadModuleExports();
          const service = readExportValue(moduleExports, testCase.exportName);
          const result = await Promise.resolve(service(...testCase.args));
          expect({
            source: SOURCE_PATH,
            scenario: 'node-service',
            confidence: testCase.confidence,
            exportName: testCase.exportName,
            args: testCase.args,
            result: normalizeBehaviorValue(result)
          }).toMatchSnapshot();
        });
      }
    });
  }
});
`;
}

function flattenScenarioCases(scenarios, kind) {
  const scenario = scenarios.find((candidate) => candidate.kind === kind);
  return scenario && Array.isArray(scenario.cases) ? scenario.cases : [];
}

function writeManagedFile(filePath, content, options = {}) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf8');
    if (existing === content) {
      return;
    }

    if (!existing.startsWith(GENERATED_MARKER) && !options.force) {
      throw new Error(
        `Refusing to overwrite non-Themis file: ${filePath}. Use --force to replace it.`
      );
    }
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function removePlannedFiles(plans, outputDir) {
  const removedFiles = [];

  for (const plan of plans) {
    if (!fs.existsSync(plan.file)) {
      continue;
    }

    const existing = fs.readFileSync(plan.file, 'utf8');
    if (!existing.startsWith(GENERATED_MARKER)) {
      continue;
    }

    fs.rmSync(plan.file, { force: true });
    removedFiles.push(plan.file);
    removeSnapshotFile(plan.file);
    pruneEmptyDirectories(path.dirname(plan.file), outputDir);
  }

  return removedFiles.sort();
}

function cleanupStaleGeneratedFiles(outputDir, expectedManagedFiles, explicitRemoved = []) {
  const removedFiles = [...explicitRemoved];

  if (!fs.existsSync(outputDir)) {
    return removedFiles.sort();
  }

  for (const filePath of walkFiles(outputDir)) {
    const basename = path.basename(filePath);
    if (basename === '.DS_Store') {
      continue;
    }

    const existing = fs.readFileSync(filePath, 'utf8');
    if (!existing.startsWith(GENERATED_MARKER)) {
      continue;
    }

    if (expectedManagedFiles.has(safeRealpath(filePath))) {
      continue;
    }

    fs.rmSync(filePath, { force: true });
    removedFiles.push(filePath);

    if (filePath.endsWith('.generated.test.js')) {
      removeSnapshotFile(filePath);
    }

    pruneEmptyDirectories(path.dirname(filePath), outputDir);
  }

  return [...new Set(removedFiles)].sort();
}

function *walkFiles(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield *walkFiles(fullPath);
      continue;
    }
    if (entry.isFile()) {
      yield fullPath;
    }
  }
}

function removeSnapshotFile(testFilePath) {
  const snapshotFile = path.join(
    path.dirname(testFilePath),
    '__snapshots__',
    `${path.basename(testFilePath)}.snapshots.json`
  );
  if (fs.existsSync(snapshotFile)) {
    fs.rmSync(snapshotFile, { force: true });
    pruneEmptyDirectories(path.dirname(snapshotFile), path.dirname(testFilePath));
  }
}

function removeManagedHelper(helperFile, outputDir) {
  if (!fs.existsSync(helperFile)) {
    return false;
  }

  const existing = fs.readFileSync(helperFile, 'utf8');
  if (!existing.startsWith(GENERATED_MARKER)) {
    return false;
  }

  fs.rmSync(helperFile, { force: true });
  pruneEmptyDirectories(path.dirname(helperFile), outputDir);
  return true;
}

function pruneEmptyDirectories(startDir, stopDir) {
  let currentDir = startDir;
  while (isSubPath(currentDir, stopDir) || currentDir === stopDir) {
    if (!fs.existsSync(currentDir)) {
      break;
    }

    if (fs.readdirSync(currentDir).length > 0) {
      break;
    }

    fs.rmdirSync(currentDir);
    if (currentDir === stopDir) {
      break;
    }
    currentDir = path.dirname(currentDir);
  }
}

function serializeLiteralNode(node) {
  if (!node) {
    return undefined;
  }
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return node.text;
  }
  if (ts.isNumericLiteral(node)) {
    return Number(node.text);
  }
  if (node.kind === ts.SyntaxKind.TrueKeyword) {
    return true;
  }
  if (node.kind === ts.SyntaxKind.FalseKeyword) {
    return false;
  }
  if (node.kind === ts.SyntaxKind.NullKeyword) {
    return null;
  }
  if (ts.isArrayLiteralExpression(node)) {
    return node.elements.map((element) => serializeLiteralNode(element));
  }
  if (ts.isObjectLiteralExpression(node)) {
    const value = {};
    for (const property of node.properties) {
      if (!ts.isPropertyAssignment(property)) {
        return undefined;
      }
      const key = getPropertyName(property.name);
      if (!key) {
        return undefined;
      }
      value[key] = serializeLiteralNode(property.initializer);
    }
    return value;
  }
  return undefined;
}

function readLiteralNodeValue(node) {
  if (!node) {
    return undefined;
  }
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return node.text;
  }
  if (ts.isNumericLiteral(node)) {
    return Number(node.text);
  }
  if (node.kind === ts.SyntaxKind.TrueKeyword) {
    return true;
  }
  if (node.kind === ts.SyntaxKind.FalseKeyword) {
    return false;
  }
  return undefined;
}

function readBindingName(node, index) {
  if (ts.isIdentifier(node)) {
    return node.text;
  }
  if (ts.isObjectBindingPattern(node)) {
    return `object${index + 1}`;
  }
  if (ts.isArrayBindingPattern(node)) {
    return `array${index + 1}`;
  }
  return `arg${index + 1}`;
}

function cloneSerializable(value) {
  if (value === undefined) {
    return undefined;
  }
  return JSON.parse(JSON.stringify(value));
}

function isPlainObject(value) {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function createSourceHash(source) {
  return crypto.createHash('sha1').update(source).digest('hex');
}

function normalizeRelativeModule(relativePath) {
  const normalized = normalizePath(relativePath);
  return normalized.startsWith('.') ? normalized : `./${normalized}`;
}

function normalizePath(value) {
  return String(value).split(path.sep).join('/');
}

function isSubPath(targetPath, parentPath) {
  const relative = path.relative(parentPath, targetPath);
  return relative !== '' && !relative.startsWith('..') && !path.isAbsolute(relative);
}

function isSameOrSubPath(targetPath, parentPath) {
  return path.resolve(targetPath) === path.resolve(parentPath) || isSubPath(targetPath, parentPath);
}

function safeRealpath(targetPath) {
  try {
    return fs.realpathSync.native(targetPath);
  } catch (error) {
    return path.resolve(targetPath);
  }
}

function formatPathForDisplay(projectRoot, targetPath) {
  const relative = path.relative(projectRoot, targetPath);
  return relative && !relative.startsWith('..') ? normalizePath(relative) : targetPath;
}

module.exports = {
  generateTestsFromSource,
  buildGeneratePayload,
  buildGenerateHandoff,
  writeGenerateArtifacts,
  GENERATED_MARKER,
  GENERATED_HELPER_NAME,
  GENERATED_MAP_ARTIFACT,
  GENERATED_RESULT_ARTIFACT,
  GENERATED_HANDOFF_ARTIFACT
};
